import { Company } from '@/components/CompaniesPage';

export const companiesData: Company[] = [
  {
    id: 'comp-001',
    name: 'actandacre',
    domain: 'actandacre.com',
    icon_color: 'bg-slate-600',
    last_meeting: '2024-12-01',
    customer_profile: null,
  },
  {
    id: 'comp-002',
    name: 'adaptive sound technologies, inc.',
    domain: 'asoundtech.com',
    icon_color: 'bg-purple-400',
    last_meeting: '2024-10-13',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
  },
  {
    id: 'comp-003',
    name: 'adco medical suppliers',
    domain: 'adcopros.com',
    icon_color: 'bg-blue-500',
    last_meeting: '2024-09-19',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
  },
  {
    id: 'comp-004',
    name: 'advocare',
    domain: 'advocare.com',
    icon_color: 'bg-blue-600',
    last_meeting: '2024-11-18',
    customer_profile: null,
  },
  {
    id: 'comp-005',
    name: 'adyen',
    domain: 'adyen.com',
    icon_color: 'bg-green-500',
    last_meeting: '2024-11-20',
    customer_profile: null,
  },
  {
    id: 'comp-006',
    name: 'aletha health',
    domain: 'alethahealth.com',
    icon_color: 'bg-gray-700',
    last_meeting: '2024-09-25',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
  },
  {
    id: 'comp-007',
    name: 'allermi',
    domain: 'allermi.com',
    icon_color: 'bg-gray-500',
    last_meeting: '2024-09-19',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
  },
  {
    id: 'comp-008',
    name: 'alma',
    domain: 'alma.food',
    icon_color: 'bg-green-400',
    last_meeting: '2024-10-21',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
  },
  {
    id: 'comp-009',
    name: 'alyze.health',
    domain: 'alyze.health',
    icon_color: 'bg-purple-300',
    last_meeting: '2024-11-26',
    customer_profile: null,
  },
  {
    id: 'comp-010',
    name: 'andiemup',
    domain: 'andiemup.com',
    icon_color: 'bg-gray-800',
    last_meeting: '2024-12-08',
    customer_profile: null,
  },
  {
    id: 'comp-011',
    name: 'anker',
    domain: 'anker.com',
    icon_color: 'bg-blue-400',
    last_meeting: '2024-11-05',
    customer_profile: null,
  },
  {
    id: 'comp-012',
    name: 'anthropic',
    domain: 'anthropic.com',
    icon_color: 'bg-orange-500',
    last_meeting: '2024-10-15',
    customer_profile: 'Enterprise AI/ML',
  },
  {
    id: 'comp-013',
    name: 'appflowy',
    domain: 'appflowy.io',
    icon_color: 'bg-indigo-600',
    last_meeting: '2024-09-30',
    customer_profile: 'SMB Productivity',
  },
  {
    id: 'comp-014',
    name: 'appsmith',
    domain: 'appsmith.com',
    icon_color: 'bg-green-600',
    last_meeting: '2024-11-12',
    customer_profile: null,
  },
  {
    id: 'comp-015',
    name: 'arc',
    domain: 'arc.dev',
    icon_color: 'bg-pink-500',
    last_meeting: '2024-08-20',
    customer_profile: 'Freelance Platforms',
  },
];
