import { Company } from '@/components/CompaniesPage';

export const companiesData: Company[] = [
  {
    id: 'comp-001',
    name: 'actandacre',
    domain: 'actandacre.com',
    icon_color: 'bg-slate-600',
    last_meeting: '2024-12-01',
    next_meeting: '2024-12-15',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '201-500',
    est_revenue: '$50M-$100M',
    summary: 'Leading sustainable fashion e-commerce platform founded in 2019. They focus on eco-friendly materials and ethical production practices. Strong growth trajectory with 45% YoY increase in revenue.',
    company_overview: 'actandacre is revolutionizing the fashion industry by making sustainable, ethical fashion accessible to mainstream consumers. Founded by three environmental activists, the company operates a vertically integrated supply chain that ensures complete transparency from fabric sourcing to final packaging. Their commitment to reducing carbon footprint has resulted in achieving carbon-neutral status in 2024, ahead of most competitors.\n\nThe company has established itself as a market leader in the sustainable fashion space with a loyal customer base that spans 15+ countries. Their innovative approach combines cutting-edge e-commerce technology with environmental responsibility, attracting Gen Z and millennial consumers who prioritize sustainability. With a team of 300+ employees and plans to expand into Asia-Pacific markets, actandacre is positioned for significant growth in the coming years.',
    product_offering: [
      'Sustainable apparel and accessories made from organic materials',
      'Custom design and personalization services',
      'B2B wholesale solutions for retail partners',
      'Subscription box service with curated seasonal collections',
      'Eco-friendly packaging and carbon-neutral shipping',
    ],
    recent_news: [
      { date: 'Feb 10, 2026', title: 'Announced expansion into European markets', source: 'https://techcrunch.com/actandacre-europe' },
      { date: 'Jan 15, 2026', title: 'Secured Series B funding of $25M', source: 'https://crunchbase.com/organization/actandacre' },
      { date: 'Dec 22, 2025', title: 'Launched new sustainable packaging initiative', source: 'https://www.sustainablefashionmag.com/actandacre' },
    ],
    total_funding_raised: '$45M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$25M',
    latest_funding_date: 'Jan 15, 2026',
    deal: 'Deal with actandacre',
    deal_momentum: 'Strong',
    primary_contact: 'Sarah Chen',
    primary_contact_color: 'blue-400',
    linkedin_url: 'https://www.linkedin.com/company/actandacre',
    industry: 'Apparel manufacturing',
    company_type: 'Private',
    location: 'Portland, Oregon, United States',
    tech_stack: 'React, Node.js, PostgreSQL, AWS, Stripe, Shopify',
    hiring_signals: [
      { role: 'Software Engineer', count: 3 },
      { role: 'Product Manager', count: 1 },
      { role: 'Supply Chain Analyst', count: 2 },
    ],
    contacts: [
      {
        name: 'Sarah Chen',
        email: 'sarah.chen@actandacre.com',
        job_title: 'Chief Operating Officer',
        avatar_color: 'blue-400',
        persona: 'Finance/Operations Executive',
        role_in_buying_process: 'Champion',
      },
      {
        name: 'Michael Rodriguez',
        email: 'michael.rodriguez@actandacre.com',
        job_title: 'VP of Supply Chain',
        avatar_color: 'green-500',
        persona: 'Technical Implementation Lead',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 15',
        title: 'Product demo & feature roadmap',
        time: '2:00 PM - 2:45 PM',
        attendees: [
          { name: 'Sarah Chen', contact_role: 'buyer' },
          { name: 'Michael Rodriguez', contact_role: 'buyer' },
          { name: 'Alex Rivera', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 28',
        title: 'Initial discovery call',
        time: '1:00 PM - 1:30 PM',
        attendees: [
          { name: 'Sarah Chen', contact_role: 'buyer' },
          { name: 'Alex Rivera', contact_role: 'seller' },
        ],
      },
      {
        date: 'NOV 10',
        title: 'Technical requirements review',
        time: '3:00 PM - 4:00 PM',
        attendees: [
          { name: 'Michael Rodriguez', contact_role: 'buyer' },
          { name: 'David Kim', contact_role: 'seller' },
          { name: 'Alex Rivera', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-002',
    name: 'adaptive sound technologies, inc.',
    domain: 'asoundtech.com',
    icon_color: 'bg-purple-400',
    last_meeting: '2024-10-13',
    next_meeting: '2024-12-20',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$10M-$25M',
    summary: 'Innovator in adaptive audio technology for wellness applications. Serves over 50,000 health practitioners nationwide. Expanding distribution through retail partnerships.',
    company_overview: 'Adaptive Sound Technologies stands out in the wellness industry by combining neuroscience research with audio technology to create personalized wellness experiences. Their proprietary algorithms adjust audio frequencies based on individual physiological responses, making them uniquely positioned in a rapidly growing market. The company\'s peer-reviewed research has been featured in leading wellness publications, establishing credibility and trust among health professionals.\n\nWith a customer base spanning yoga studios, meditation centers, corporate wellness programs, and telehealth platforms, Adaptive Sound Technologies has achieved strong product-market fit. Their successful integration with major wellness platforms and recent retail partnerships signal strong momentum. The company is experiencing 40% YoY growth and has recently strengthened its leadership team with industry veterans from meditation app companies and sleep technology firms.',
    product_offering: [
      'Proprietary adaptive audio profiles for meditation and sleep',
      'White-label solutions for wellness app integrations',
      'Hardware devices with embedded audio technology',
      'Professional training programs for practitioners',
    ],
    recent_news: [
      { date: 'Feb 8, 2026', title: 'Partnered with major wellness retailer for nationwide distribution', source: 'https://wellnessnews.com/adaptive-sound-partnership' },
      { date: 'Jan 20, 2026', title: 'Launched new audio profiles for meditation and sleep', source: 'https://www.asoundtech.com/press/new-profiles' },
    ],
    total_funding_raised: '$12M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$12M',
    latest_funding_date: 'Dec 3, 2025',
    deal: 'Deal with adaptive sound technologies, inc.',
    deal_momentum: 'Stalled',
    primary_contact: 'James Miller',
    primary_contact_color: 'purple-400',
    linkedin_url: 'https://www.linkedin.com/company/adaptive-sound-technologies',
    industry: 'Audio and video equipment manufacturing',
    company_type: 'Private',
    location: 'San Francisco, California, United States',
    tech_stack: 'Python, Django, React, WebRTC, TensorFlow, AWS',
    hiring_signals: [
      { role: 'Audio Engineer', count: 2 },
      { role: 'Machine Learning Engineer', count: 1 },
    ],
    contacts: [
      {
        name: 'James Miller',
        email: 'james.miller@asoundtech.com',
        job_title: 'Chief Technology Officer',
        avatar_color: 'purple-400',
        persona: 'Technical Founder/Decision Maker',
        role_in_buying_process: 'Economic Buyer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 20',
        title: 'Technical architecture review',
        time: '3:00 PM - 3:30 PM',
        attendees: [
          { name: 'James Miller', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'OCT 13',
        title: 'Kick-off meeting & requirements gathering',
        time: '2:00 PM - 2:45 PM',
        attendees: [
          { name: 'James Miller', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-003',
    name: 'adco medical suppliers',
    domain: 'adcopros.com',
    icon_color: 'bg-blue-500',
    last_meeting: '2024-09-19',
    next_meeting: '2024-12-18',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '201-500',
    est_revenue: '$100M-$250M',
    summary: 'Established medical supply distributor serving 200+ clinics and healthcare facilities. Known for reliable logistics and competitive pricing. Currently modernizing their operations.',
    company_overview: 'adco Medical Suppliers has been a trusted healthcare logistics partner for over 30 years, building an extensive network of supplier relationships and distribution infrastructure. Their deep expertise in healthcare operations and regulatory compliance has made them an indispensable partner for mid-sized and large medical facilities. Recently, under new leadership, the company launched a comprehensive digital transformation initiative to modernize their legacy systems and improve customer experience.\n\nThe company operates a nationwide network of 12 distribution centers with same-day delivery capabilities in major metropolitan areas. Their recent investments in warehouse automation and supply chain optimization have positioned them to compete with larger players while maintaining the personalized service that long-time customers value. With a strong balance sheet and consistent cash flow, adco Medical Suppliers is well-positioned to weather market changes and invest in growth initiatives.',
    product_offering: [
      'Wide range of medical supplies and equipment',
      'Same-day delivery in major metropolitan areas',
      'Inventory management and automated ordering systems',
      'Healthcare facility consulting services',
      'Competitive bulk pricing programs',
    ],
    recent_news: [
      { date: 'Feb 5, 2026', title: 'Upgraded warehouse automation systems', source: 'https://supplychaintoday.com/adco-automation' },
      { date: 'Jan 12, 2026', title: 'Expanded service coverage to 3 new states', source: 'https://www.adcopros.com/expansion-announcement' },
      { date: 'Dec 18, 2025', title: 'Achieved ISO 13485 Medical Device Quality certification', source: 'https://medicalsupplyjournal.com/adco-iso-cert' },
    ],
    total_funding_raised: '$85M',
    num_funding_rounds: 3,
    latest_funding_stage: 'Series C',
    latest_funding_round: '$40M',
    latest_funding_date: 'Nov 20, 2025',
    deal: 'Deal with adco medical suppliers',
    deal_momentum: 'At risk',
    primary_contact: 'Emily Davis',
    primary_contact_color: 'green-400',
    linkedin_url: 'https://www.linkedin.com/company/adco-medical-suppliers',
    industry: 'Medical equipment manufacturing',
    company_type: 'Private',
    location: 'Boston, Massachusetts, United States',
    tech_stack: 'Java, Spring Boot, Oracle Database, Azure, SAP',
    hiring_signals: [
      { role: 'Warehouse Manager', count: 4 },
      { role: 'Java Developer', count: 2 },
      { role: 'Business Analyst', count: 1 },
    ],
    contacts: [
      {
        name: 'Emily Davis',
        email: 'emily.davis@adcopros.com',
        job_title: 'Director of Procurement',
        avatar_color: 'green-400',
        persona: 'Operations/Implementation Manager',
        role_in_buying_process: 'Champion',
      },
      {
        name: 'Robert Thompson',
        email: 'robert.thompson@adcopros.com',
        job_title: 'Logistics Manager',
        avatar_color: 'blue-500',
        persona: 'Operations/Implementation Manager',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 18',
        title: 'Implementation planning session',
        time: '1:00 PM - 2:00 PM',
        attendees: [
          { name: 'Emily Davis', contact_role: 'buyer' },
          { name: 'Robert Thompson', contact_role: 'buyer' },
          { name: 'David Kim', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'SEP 19',
        title: 'Business requirements walkthrough',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Emily Davis', contact_role: 'buyer' },
          { name: 'David Kim', contact_role: 'seller' },
        ],
      },
      {
        date: 'AUG 15',
        title: 'Initial vendor evaluation',
        time: '2:00 PM - 2:30 PM',
        attendees: [
          { name: 'Robert Thompson', contact_role: 'buyer' },
          { name: 'David Kim', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-004',
    name: 'advocare',
    domain: 'advocare.com',
    icon_color: 'bg-blue-600',
    last_meeting: '2024-11-18',
    next_meeting: '2024-12-22',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '1001-5000',
    est_revenue: '$1B-$10B',
    summary: 'Global nutrition and wellness company with presence in 30+ countries. Operating multi-channel sales including direct, retail, and professional channels. Seeking operational efficiency improvements.',
    company_overview: 'Advocare is a diversified nutrition company with an exceptional global footprint, operating successfully across multiple distribution channels that would overwhelm most competitors. Their network of 200,000+ independent advisors generates consistent revenue through a hybrid model combining direct sales with traditional retail and online channels. The company\'s strong brand recognition and customer loyalty have been built over decades of consistent product quality and advisor support.\n\nAs a publicly traded company, Advocare is under pressure to innovate while maintaining profitability. Recent strategic initiatives include expanding their product portfolio into emerging wellness categories and investing heavily in digital capabilities to serve millennial and Gen Z consumers. Their scale—with operations in 30+ countries and partnerships with major retail chains—provides significant competitive advantages. The company is actively exploring technology partnerships to enhance their advisor platform and customer experience.',
    product_offering: [
      'Nutritional supplements and wellness products',
      'Direct-to-consumer sales and distribution network',
      'Professional advisor commission programs',
      'Retail partnerships with 5,000+ locations',
      'Online marketplace and mobile app',
    ],
    recent_news: [
      { date: 'Feb 12, 2026', title: 'Launched new product line in 15 countries', source: 'https://www.advocare.com/press/new-product-launch' },
      { date: 'Jan 28, 2026', title: 'Announced strategic partnership with global fitness chain', source: 'https://fitnessinsider.com/advocare-partnership' },
      { date: 'Jan 5, 2026', title: 'Reported Q4 revenue growth of 18% YoY', source: 'https://finance.yahoo.com/quote/ADVOCARE' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2018',
    latest_funding_date: 'May 4, 2018',
    deal: 'Deal with advocare',
    deal_momentum: 'Strong',
    primary_contact: 'Alex Johnson',
    primary_contact_color: 'pink-400',
    linkedin_url: 'https://www.linkedin.com/company/advocare',
    industry: 'Beverage manufacturing',
    company_type: 'Public',
    location: 'Houston, Texas, United States',
    tech_stack: 'C#, .NET, SQL Server, Azure, Salesforce, Tableau',
    hiring_signals: [
      { role: 'Sales Executive', count: 5 },
      { role: 'Supply Chain Specialist', count: 3 },
      { role: '.NET Developer', count: 2 },
    ],
    contacts: [
      {
        name: 'Alex Johnson',
        email: 'alex.johnson@advocare.com',
        job_title: 'VP of Operations',
        avatar_color: 'pink-400',
        persona: 'Finance/Operations Executive',
        role_in_buying_process: 'Economic Buyer',
      },
      {
        name: 'Jennifer Lee',
        email: 'jennifer.lee@advocare.com',
        job_title: 'Senior Manager, Product Development',
        avatar_color: 'amber-400',
        persona: 'Marketing/Growth Leader',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 22',
        title: 'Executive steering committee',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Alex Johnson', contact_role: 'buyer' },
          { name: 'Jennifer Lee', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 18',
        title: 'Strategic alignment meeting',
        time: '9:00 AM - 10:00 AM',
        attendees: [
          { name: 'Alex Johnson', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-005',
    name: 'adyen',
    domain: 'adyen.com',
    icon_color: 'bg-green-500',
    last_meeting: '2024-11-20',
    next_meeting: '2024-12-25',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '5001-10000',
    est_revenue: '$10B+',
    summary: 'Leading fintech payment processor handling $500B+ in annual transaction volume. Serves 5,000+ enterprise customers globally. Continuously expanding platform capabilities.',
    company_overview: 'Adyen has emerged as one of the world\'s most sophisticated payment processors by combining cutting-edge technology infrastructure with deep expertise in global payments complexity. Their proprietary fraud detection algorithms and risk management platform protect billions in daily transactions while enabling merchants to optimize conversion rates. The company\'s global perspective—with offices in 80+ cities—enables them to serve multinational enterprises with localized support and compliance expertise.\n\nAs a publicly traded company, Adyen continues to invest heavily in AI-powered solutions, expanding emerging payment methods, and building vertical-specific offerings for industries like travel and retail. Their recent launches of embedded finance solutions and white-label payment platforms demonstrate a strategic shift toward becoming a comprehensive fintech infrastructure provider. With consistent revenue growth and strong margins, Adyen remains a favorite among institutional investors and is well-positioned to capture the shift toward digital payments globally.',
    product_offering: [
      'Global payment processing across 195+ countries',
      'AI-powered fraud detection and risk management',
      'Multi-currency and multi-payment method support',
      'Enterprise-grade API and integration solutions',
      'Real-time reporting and analytics dashboard',
    ],
    recent_news: [
      { date: 'Feb 14, 2026', title: 'Introduced AI-powered fraud detection system', source: 'https://www.adyen.com/blog/ai-fraud-detection' },
      { date: 'Jan 30, 2026', title: 'Expanded coverage to 195 countries and territories', source: 'https://finance.yahoo.com/quote/ADYEN' },
      { date: 'Jan 8, 2026', title: 'Achieved $1 trillion cumulative transaction milestone', source: 'https://www.adyen.com/press/trillion-milestone' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2018',
    latest_funding_date: 'Jun 7, 2018',
    deal: 'Deal with adyen',
    deal_momentum: 'Active',
    primary_contact: 'Maria Lopez',
    primary_contact_color: 'amber-400',
    linkedin_url: 'https://www.linkedin.com/company/adyen',
    industry: 'Financial services',
    company_type: 'Public',
    location: 'Amsterdam, North Holland, Netherlands',
    tech_stack: 'Go, Kotlin, PostgreSQL, AWS, Kubernetes, Grafana',
    hiring_signals: [
      { role: 'Backend Engineer', count: 6 },
      { role: 'Security Engineer', count: 3 },
      { role: 'DevOps Engineer', count: 2 },
    ],
    contacts: [
      {
        name: 'Maria Lopez',
        email: 'maria.lopez@adyen.com',
        job_title: 'Head of Enterprise Solutions',
        avatar_color: 'amber-400',
        persona: 'Technical Founder/Decision Maker',
        role_in_buying_process: 'Economic Buyer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 25',
        title: 'Q1 2026 planning session',
        time: '11:00 AM - 12:00 PM',
        attendees: [
          { name: 'Maria Lopez', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 20',
        title: 'Enterprise solution demo',
        time: '2:00 PM - 3:00 PM',
        attendees: [
          { name: 'Maria Lopez', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-006',
    name: 'aletha health',
    domain: 'alethahealth.com',
    icon_color: 'bg-gray-700',
    last_meeting: '2024-09-25',
    next_meeting: '2024-12-19',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$5M-$10M',
    summary: 'Digital health platform providing personalized wellness programs. Partnered with 15 major employers for employee health initiatives. Growing user base of 75,000+.',
    company_overview: 'Aletha Health represents a new generation of digital health companies focused on preventive wellness rather than reactive treatment. Their AI-driven personalization engine analyzes individual health data to deliver highly targeted recommendations that resonate with users, resulting in exceptional engagement metrics compared to industry averages. Partnerships with Fortune 500 companies provide stable, recurring revenue and credibility in the enterprise market.\n\nThe company has successfully positioned itself at the intersection of healthcare, fitness, and consumer wellness—a rapidly growing market driven by employer demand for reducing healthcare costs. Their recent mobile app redesign and expansion into wearable device integrations have significantly improved user retention. With backing from leading healthtech investors and a clear path to profitability, Aletha Health is poised to become a market leader in corporate wellness platforms.',
    product_offering: [
      'Personalized wellness coaching and health tracking',
      'AI-powered health recommendations',
      'Integration with major wearable devices',
      'Corporate wellness program management',
      'HIPAA-compliant mobile app',
    ],
    recent_news: [
      { date: 'Feb 3, 2026', title: 'Partnered with 3 Fortune 500 companies', source: 'https://www.alethahealth.com/press/fortune500-partnerships' },
      { date: 'Jan 10, 2026', title: 'Launched mobile app v2.0 with AI coaching', source: 'https://apps.apple.com/us/app/aletha-health/id123456789' },
    ],
    total_funding_raised: '$8M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$5M',
    latest_funding_date: 'Sep 12, 2024',
    deal: 'Deal with aletha health',
    deal_momentum: 'Strong',
    primary_contact: 'David Park',
    primary_contact_color: 'red-400',
    linkedin_url: 'https://www.linkedin.com/company/aletha-health',
    industry: 'Outpatient care centers',
    company_type: 'Nonprofit',
    location: 'Denver, Colorado, United States',
    tech_stack: 'React Native, Firebase, Python, TensorFlow, HIPAA compliance',
    hiring_signals: [
      { role: 'Mobile Developer', count: 2 },
      { role: 'Health Coach', count: 4 },
      { role: 'Data Scientist', count: 1 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 19',
        title: 'Corporate wellness program review',
        time: '1:30 PM - 2:30 PM',
        attendees: [
          { name: 'David Park', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'SEP 25',
        title: 'Health platform integration discussion',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'David Park', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-007',
    name: 'allermi',
    domain: 'allermi.com',
    icon_color: 'bg-gray-500',
    last_meeting: '2024-09-19',
    next_meeting: '2024-12-16',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '201-500',
    est_revenue: '$25M-$50M',
    summary: 'Specialty allergen-free personal care brand disrupting the beauty space. DTC-focused with strong social media presence. Projected 60% revenue growth this year.',
    company_overview: 'Allermi tapped into an underserved niche in the beauty industry by focusing exclusively on allergen-free formulations without sacrificing efficacy or aesthetics. Their founder\'s personal experience with severe allergies inspired a mission-driven company that resonates deeply with consumers seeking safer, cleaner beauty alternatives. A massive social media following (1M+ followers) demonstrates powerful organic demand and authentic customer advocacy.\n\nThe company\'s recent expansion into 200+ retail locations represents a significant milestone, validating their transition from pure DTC to omnichannel distribution. Their subscription box model provides predictable recurring revenue while driving higher customer lifetime value. With venture backing from beauty-focused investors and a proven product-market fit, Allermi is well-positioned to scale nationally and internationally while competing against larger incumbents by owning the allergen-free positioning.',
    product_offering: [
      'Allergen-free skincare and cosmetics line',
      'Direct-to-consumer e-commerce platform',
      'Retail partnerships and distribution network',
      'Subscription beauty box service',
      'Influencer collaboration and exclusive collections',
    ],
    recent_news: [
      { date: 'Feb 6, 2026', title: 'Reached 1M social media followers milestone', source: 'https://www.instagram.com/allermi_beauty/' },
      { date: 'Jan 22, 2026', title: 'Launched in 200+ retail locations nationwide', source: 'https://www.allermi.com/retail-locations' },
      { date: 'Dec 28, 2025', title: 'Featured in major beauty magazine', source: 'https://www.beautyindustrymagazine.com/allermi-feature' },
    ],
    total_funding_raised: '$32M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$18M',
    latest_funding_date: 'Aug 7, 2024',
    deal: 'Deal with allermi',
    deal_momentum: 'Closed',
    primary_contact: 'Jessica Wong',
    primary_contact_color: 'cyan-400',
    linkedin_url: 'https://www.linkedin.com/company/allermi',
    industry: 'Personal care product manufacturing',
    company_type: 'Private',
    location: 'Los Angeles, California, United States',
    tech_stack: 'Vue.js, Express.js, MongoDB, AWS Lambda, Klaviyo, Shopify Plus',
    hiring_signals: [
      { role: 'Marketing Manager', count: 2 },
      { role: 'Brand Designer', count: 1 },
      { role: 'Content Creator', count: 3 },
    ],
    past_meetings: [
      {
        date: 'SEP 19',
        title: 'Beauty brand partnership discussion',
        time: '3:00 PM - 4:00 PM',
        attendees: [
          { name: 'Jessica Wong', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-008',
    name: 'alma',
    domain: 'alma.food',
    icon_color: 'bg-green-400',
    last_meeting: '2024-10-21',
    next_meeting: '2024-12-17',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$1M-$10M',
    summary: 'Organic plant-based food company founded in 2018. Direct-to-consumer model with growing wholesale partnerships. Expanding product line across 12 US states.',
    company_overview: 'Alma exemplifies the new wave of direct-to-consumer food companies leveraging sustainability and transparency as core differentiators. Founded by environmental scientists and nutrition experts, the company maintains an unwavering commitment to organic sourcing and sustainable practices that appeal to health-conscious and environmentally aware consumers. Their Berlin headquarters and European supply chain relationships give them unique advantages in sourcing premium organic ingredients.\n\nThe company\'s subscription box model generates predictable revenue while building community around sustainable eating. Recent retail partnerships with major organic chains represent validation of their product quality and brand strength. With modest funding requirements, lean operations, and strong unit economics, Alma is demonstrating that mission-driven food brands can achieve profitability without compromising their values. They are well-positioned to capitalize on the accelerating consumer shift toward plant-based diets.',
    product_offering: [
      'Certified organic plant-based food products',
      'Direct-to-consumer subscription boxes',
      'Wholesale B2B partnerships with retailers',
      'Meal planning and recipe services',
      'Sustainable packaging and eco-friendly logistics',
    ],
    recent_news: [
      { date: 'Feb 1, 2026', title: 'Expanded product line with 5 new plant-based options', source: 'https://www.alma.food/new-products' },
      { date: 'Jan 14, 2026', title: 'Secured partnership with major organic retailer chain', source: 'https://organicfoodinsider.com/alma-retail-partnership' },
    ],
    total_funding_raised: '$4.5M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Seed',
    latest_funding_round: '$4.5M',
    latest_funding_date: 'Mar 15, 2023',
    deal: 'Deal with alma',
    deal_momentum: 'Active',
    primary_contact: 'Michael Chen',
    primary_contact_color: 'indigo-400',
    linkedin_url: 'https://www.linkedin.com/company/alma-organic-food',
    industry: 'Food and beverage manufacturing',
    company_type: 'Private',
    location: 'Berlin, Berlin, Germany',
    tech_stack: 'Next.js, TypeScript, Supabase, Stripe, SendGrid, GCP',
    hiring_signals: [
      { role: 'Operations Manager', count: 1 },
      { role: 'Product Designer', count: 1 },
      { role: 'Full Stack Developer', count: 2 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 17',
        title: 'Organic retail partnership proposal',
        time: '2:00 PM - 3:00 PM',
        attendees: [
          { name: 'Michael Chen', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'OCT 21',
        title: 'Product quality & sourcing discussion',
        time: '11:00 AM - 12:00 PM',
        attendees: [
          { name: 'Michael Chen', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-009',
    name: 'alyze.health',
    domain: 'alyze.health',
    icon_color: 'bg-purple-300',
    last_meeting: '2024-11-26',
    next_meeting: '2024-12-21',
    customer_profile: 'Health Tech Growth-Stage Partnership-Ready',
    employee_count: '201-500',
    est_revenue: '$10M-$25M',
    summary: 'AI-powered health analytics platform for predictive diagnostics. Recently secured Series A funding. Partnering with 8 healthcare systems in pilot programs.',
    company_overview: 'Alyze.Health represents the convergence of healthcare and artificial intelligence, solving a critical problem in modern medicine: early detection of disease. Their machine learning models are trained on millions of de-identified patient records, enabling predictive capabilities that exceed traditional diagnostic approaches. Recent peer-reviewed publications in top-tier medical journals validate their scientific rigor and establish credibility in the conservative healthcare community.\n\nThe company\'s pilot partnerships with major healthcare systems demonstrate strong clinical validation and provider adoption potential. Their focus on HIPAA compliance and privacy protection has enabled them to build trust with hospitals and health systems concerned about data security. With Series A funding secured and a clear path to commercialization through healthcare system partnerships, Alyze.Health is positioned to transform how diseases are diagnosed and managed globally.',
    product_offering: [
      'Predictive diagnostics using machine learning',
      'Electronic health record integration',
      'Clinical decision support system',
      'Actionable insights for healthcare providers',
      'HIPAA-compliant cloud platform',
    ],
    recent_news: [
      { date: 'Feb 11, 2026', title: 'Secured $15M Series A funding round', source: 'https://crunchbase.com/organization/alyze-health' },
      { date: 'Jan 26, 2026', title: 'Expanded pilot programs to 8 healthcare systems', source: 'https://www.alyze.health/press/pilot-expansion' },
      { date: 'Jan 2, 2026', title: 'Published research in peer-reviewed medical journal', source: 'https://www.pubmed.gov/alyze-research' },
    ],
    total_funding_raised: '$15M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$15M',
    latest_funding_date: 'Feb 11, 2026',
    deal: 'Deal with alyze.health',
    deal_momentum: 'Strong',
    primary_contact: 'Rachel Martinez',
    primary_contact_color: 'orange-400',
    linkedin_url: 'https://www.linkedin.com/company/alyze-health',
    industry: 'Biotechnology research',
    company_type: 'Educational',
    location: 'Cambridge, Cambridgeshire, United Kingdom',
    tech_stack: 'Python, PyTorch, FastAPI, PostgreSQL, Docker, Kubernetes, GCP',
    hiring_signals: [
      { role: 'Data Scientist', count: 3 },
      { role: 'Clinical Researcher', count: 2 },
      { role: 'Healthcare Solutions Architect', count: 1 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 21',
        title: 'Healthcare system pilot program review',
        time: '9:00 AM - 10:00 AM',
        attendees: [
          { name: 'Rachel Martinez', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 26',
        title: 'AI diagnostics demo & clinical validation',
        time: '2:00 PM - 3:30 PM',
        attendees: [
          { name: 'Rachel Martinez', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-010',
    name: 'andiemup',
    domain: 'andiemup.com',
    icon_color: 'bg-gray-800',
    last_meeting: '2024-12-08',
    next_meeting: '2024-12-23',
    customer_profile: 'Mid-Market Multi-Channel Operators',
    employee_count: '201-500',
    est_revenue: '$250M-$500M',
    summary: 'Omnichannel retail platform connecting 300+ independent brands. Operates both B2B2C marketplace and white-label solutions. Processing $20M+ in monthly transactions.',
    company_overview: 'Andiemup has cracked the code on supporting independent brands at scale through a sophisticated marketplace infrastructure that abstracts away operational complexity. Their platform automates inventory management, fulfillment, and multi-channel selling, enabling small brands to compete effectively against larger competitors. The company\'s white-label offerings give them access to an entirely new customer segment of retailers looking to launch online channels without building from scratch.\n\nWith $20M+ in monthly transaction volume and 300+ connected brands, Andiemup has achieved critical mass while maintaining strong unit economics. Recent funding rounds at increasing valuations reflect investor confidence in their business model and market opportunity. Their recent pivot toward enterprise partnerships signals an evolution beyond marketplace toward becoming essential infrastructure for omnichannel retail, positioning them for significant scale in the multi-channel commerce era.',
    product_offering: [
      'B2B2C marketplace for independent brands',
      'White-label e-commerce solutions',
      'Inventory management and fulfillment services',
      'Multi-channel sales integration',
      'Advanced analytics and business intelligence',
    ],
    recent_news: [
      { date: 'Feb 7, 2026', title: 'Onboarded 50 new independent brands', source: 'https://www.andiemup.com/press/brand-onboarding' },
      { date: 'Jan 19, 2026', title: 'Launched white-label solution for enterprise partners', source: 'https://www.andiemup.com/enterprise' },
      { date: 'Dec 28, 2025', title: 'Hit $20M monthly transaction volume milestone', source: 'https://techcrunch.com/andiemup-milestone' },
    ],
    total_funding_raised: '$120M',
    num_funding_rounds: 4,
    latest_funding_stage: 'Series C',
    latest_funding_round: '$60M',
    latest_funding_date: 'Oct 18, 2025',
    deal: 'Deal with andiemup',
    deal_momentum: 'Active',
    primary_contact: 'Kevin Thompson',
    primary_contact_color: 'blue-500',
    linkedin_url: 'https://www.linkedin.com/company/andiemup',
    industry: 'Retail',
    company_type: 'Public_Subsidiary',
    location: 'New York, New York, United States',
    tech_stack: 'React, Node.js, MySQL, Redis, AWS, Elasticsearch, Datadog',
    hiring_signals: [
      { role: 'Frontend Engineer', count: 4 },
      { role: 'Backend Engineer', count: 3 },
      { role: 'QA Engineer', count: 2 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 23',
        title: 'Marketplace integration planning',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Kevin Thompson', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'DEC 8',
        title: 'White-label solution discovery',
        time: '3:00 PM - 4:00 PM',
        attendees: [
          { name: 'Kevin Thompson', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-011',
    name: 'anker',
    domain: 'anker.com',
    icon_color: 'bg-blue-400',
    last_meeting: '2024-11-05',
    next_meeting: '2024-12-19',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '1001-5000',
    est_revenue: '$500M-$1B',
    summary: 'Consumer electronics brand known for charging accessories and smart home products. Global reach with operations in 80+ countries. Selling through 5,000+ retail locations.',
    company_overview: 'Anker has achieved remarkable success by focusing on products where consumers have high price sensitivity but quality expectations: charging accessories and power solutions. Their obsessive focus on engineering excellence, combined with aggressive pricing and smart direct-to-consumer strategies, has enabled them to dominate a category many thought commoditized. Recent expansion into IoT and smart home products demonstrates their successful execution of adjacent category expansion.\n\nPublicly traded since 2021, Anker operates with both startup agility and enterprise scale. Their presence in 80+ countries and 5,000+ retail locations provides unmatched distribution advantages. Recent investments in R&D for next-generation fast-charging and smart home technologies position them to compete in higher-margin product categories. With a loyal customer base and strong brand recognition, particularly among tech enthusiasts, Anker is well-positioned to expand beyond accessories into a broader consumer electronics powerhouse.',
    product_offering: [
      'Fast-charging technology and power accessories',
      'Smart home device ecosystem',
      'Consumer electronics and mobile accessories',
      'IoT connectivity solutions',
      'Global retail and online distribution',
    ],
    recent_news: [
      { date: 'Feb 9, 2026', title: 'Launched new smart home ecosystem with 12 products', source: 'https://www.anker.com/press/smart-home-launch' },
      { date: 'Jan 16, 2026', title: 'Expanded into 15 new markets in Asia-Pacific', source: 'https://techasia.com/anker-expansion' },
      { date: 'Dec 20, 2025', title: 'Achieved record Q4 revenue of $500M', source: 'https://finance.yahoo.com/quote/ANKER' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2021',
    latest_funding_date: 'Dec 15, 2021',
    deal: 'Deal with anker',
    deal_momentum: 'Strong',
    primary_contact: 'Sophie Anderson',
    primary_contact_color: 'green-500',
    linkedin_url: 'https://www.linkedin.com/company/anker',
    industry: 'Computer hardware manufacturing',
    company_type: 'Public',
    location: 'Shenzhen, Guangdong, China',
    tech_stack: 'Flutter, Dart, Java, Go, AWS, Kubernetes, Jenkins',
    hiring_signals: [
      { role: 'Product Engineer', count: 5 },
      { role: 'Supply Chain Manager', count: 2 },
      { role: 'Sales Engineer', count: 3 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 19',
        title: 'Smart home product roadmap discussion',
        time: '1:00 PM - 2:00 PM',
        attendees: [
          { name: 'Sophie Anderson', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 5',
        title: 'Distribution channel expansion',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Sophie Anderson', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-012',
    name: 'anthropic',
    domain: 'anthropic.com',
    icon_color: 'bg-orange-500',
    last_meeting: '2024-10-15',
    next_meeting: '2024-12-24',
    customer_profile: 'Enterprise AI/ML',
    employee_count: '201-500',
    est_revenue: '$100M-$250M',
    summary: 'Leading AI research company specializing in large language models. Serving 500+ enterprise customers with Claude AI platform. Growing $100M+ in annual revenue.',
    company_overview: 'Anthropic is at the forefront of AI safety research while building commercially successful AI products—a rare combination that positions them uniquely in the rapidly evolving AI landscape. Founded by former OpenAI leaders, the company has attracted world-class AI researchers committed to developing safe, beneficial AI systems. Their Claude models have earned acclaim for their reasoning capabilities, accuracy, and alignment with human values.\n\nWith backing from leading technology companies and venture investors at a $20B+ valuation, Anthropic has the resources to invest in long-term AI safety research while capturing near-term market opportunities. Recent funding rounds and customer acquisitions demonstrate strong enterprise adoption and confidence in their technology. Their transparent approach to AI capabilities and limitations has built unique trust with enterprise customers and policymakers, positioning them as a credible voice in AI governance conversations. As AI becomes increasingly central to enterprise strategy, Anthropic\'s combination of technical excellence and safety focus is a significant competitive advantage.',
    product_offering: [
      'Claude AI large language models',
      'API access for enterprise applications',
      'Custom AI solutions and consulting',
      'Safety-focused AI implementation',
      'Multi-modal AI capabilities',
    ],
    recent_news: [
      { date: 'Feb 13, 2026', title: 'Released Claude 4 with enhanced reasoning capabilities', source: 'https://www.anthropic.com/news/claude-4' },
      { date: 'Jan 29, 2026', title: 'Announced $1B funding round at $20B valuation', source: 'https://techcrunch.com/anthropic-funding' },
      { date: 'Jan 8, 2026', title: 'Crossed 500+ enterprise customers milestone', source: 'https://www.anthropic.com/blog/enterprise-milestone' },
    ],
    total_funding_raised: '$5.3B',
    num_funding_rounds: 5,
    latest_funding_stage: 'Series D',
    latest_funding_round: '$1B',
    latest_funding_date: 'Jan 29, 2026',
    deal: 'Deal with anthropic',
    deal_momentum: 'Strong',
    primary_contact: 'Christopher Lee',
    primary_contact_color: 'purple-500',
    linkedin_url: 'https://www.linkedin.com/company/anthropic',
    industry: 'Biotechnology research',
    company_type: 'Private',
    location: 'San Francisco, California, United States',
    tech_stack: 'Python, JAX, CUDA, Cloud TPU, Slack API, Figma',
    hiring_signals: [
      { role: 'AI Research Engineer', count: 4 },
      { role: 'ML Engineer', count: 3 },
      { role: 'Systems Engineer', count: 2 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 24',
        title: 'Claude AI integration planning',
        time: '11:00 AM - 12:30 PM',
        attendees: [
          { name: 'Christopher Lee', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'OCT 15',
        title: 'AI safety & capabilities demo',
        time: '2:00 PM - 3:30 PM',
        attendees: [
          { name: 'Christopher Lee', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-013',
    name: 'appflowy',
    domain: 'appflowy.io',
    icon_color: 'bg-indigo-600',
    last_meeting: '2024-09-30',
    next_meeting: '2024-12-20',
    customer_profile: 'SMB Productivity',
    employee_count: '201-500',
    est_revenue: '$5M-$10M',
    summary: 'Open-source productivity platform competing with Notion and Airtable. Self-hosted and cloud options available. Growing community of 50,000+ active users.',
    company_overview: 'AppFlowy challenges the monopoly of closed-source productivity platforms by offering a genuinely open-source alternative with impressive feature parity to Notion. Their open-source approach has resonated deeply with developers and organizations concerned about vendor lock-in and data privacy. With 50,000+ active community members and a vibrant developer ecosystem, AppFlowy has demonstrated strong product-market fit in the open-source segment.\n\nRecent launches of AppFlowy Cloud provide a commercial path while maintaining open-source values, enabling the company to monetize without alienating their community. Their rapid feature development and responsiveness to community feedback have positioned them as a credible long-term alternative to incumbent platforms. As enterprises increasingly prioritize data sovereignty and open standards, AppFlowy\'s positioned to capture significant market share from organizations looking for privacy-first productivity solutions.',
    product_offering: [
      'Open-source database and productivity suite',
      'Self-hosted and cloud deployment options',
      'Team collaboration and database management',
      'Enterprise features and security',
      'API and integration marketplace',
    ],
    recent_news: [
      { date: 'Feb 1, 2026', title: 'Reached 50,000 active users in open-source community', source: 'https://github.com/AppFlowy/AppFlowy' },
      { date: 'Jan 10, 2026', title: 'Launched AppFlowy Cloud with enterprise features', source: 'https://appflowy.io/blog/cloud-launch' },
    ],
    total_funding_raised: '$3.2M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Seed',
    latest_funding_round: '$3.2M',
    latest_funding_date: 'Jul 22, 2022',
    deal: 'Deal with appflowy',
    deal_momentum: 'Active',
    primary_contact: 'Nicole Brown',
    primary_contact_color: 'pink-500',
    linkedin_url: 'https://www.linkedin.com/company/appflowy',
    industry: 'Software development',
    company_type: 'Private',
    location: 'Singapore, Singapore, Singapore',
    tech_stack: 'Rust, Flutter, Firebase, PostgreSQL, WebAssembly, Self-hosted',
    hiring_signals: [
      { role: 'Rust Developer', count: 2 },
      { role: 'Community Manager', count: 1 },
      { role: 'Product Manager', count: 1 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 20',
        title: 'Open-source community feedback session',
        time: '4:00 PM - 5:00 PM',
        attendees: [
          { name: 'Nicole Brown', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'SEP 30',
        title: 'Self-hosted deployment options discussion',
        time: '1:00 PM - 2:00 PM',
        attendees: [
          { name: 'Nicole Brown', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-014',
    name: 'appsmith',
    domain: 'appsmith.com',
    icon_color: 'bg-green-600',
    last_meeting: '2024-11-12',
    next_meeting: '2024-12-26',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '201-500',
    est_revenue: '$50M-$100M',
    summary: 'Low-code internal tools platform enabling enterprises to build apps 10x faster. Adopted by 200+ Fortune 500 companies. Providing solutions for data-heavy workflows.',
    company_overview: 'Appsmith has identified and captured a massive, underserved market: the enterprise need for rapid internal tools development. By lowering barriers to entry with their low-code platform, they\'ve democratized application development for business users while still providing developers with necessary flexibility. Adoption by 200+ Fortune 500 companies validates their ability to operate at enterprise scale while maintaining product excellence.\n\nTheir focus on data-heavy workflows and recent SOC 2 certification demonstrate a commitment to enterprise requirements. Recent Series B funding provides capital to accelerate sales and product development. As enterprises face pressure to do more with less, low-code platforms like Appsmith are becoming essential infrastructure. Their strong product differentiation, enterprise customer base, and market tailwinds position them for significant growth as the low-code market rapidly expands.',
    product_offering: [
      'Low-code application development platform',
      'Pre-built connectors for enterprise systems',
      'Data management and visualization tools',
      'Role-based access control and security',
      'Rapid deployment and maintenance features',
    ],
    recent_news: [
      { date: 'Feb 14, 2026', title: 'Announced enterprise security features with SOC 2 certification', source: 'https://www.appsmith.com/blog/soc2-certification' },
      { date: 'Jan 23, 2026', title: 'Adopted by 200+ Fortune 500 companies', source: 'https://www.appsmith.com/customers' },
      { date: 'Jan 1, 2026', title: 'Raised $45M Series B funding', source: 'https://crunchbase.com/organization/appsmith' },
    ],
    total_funding_raised: '$59M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$45M',
    latest_funding_date: 'Jan 1, 2026',
    deal: 'Deal with appsmith',
    deal_momentum: 'Strong',
    primary_contact: 'Thomas Wilson',
    primary_contact_color: 'amber-500',
    linkedin_url: 'https://www.linkedin.com/company/appsmith',
    industry: 'Software development',
    company_type: 'Private',
    location: 'Toronto, Ontario, Canada',
    tech_stack: 'React, Node.js, MongoDB, TypeScript, Docker, AWS Lambda',
    hiring_signals: [
      { role: 'Full Stack Developer', count: 3 },
      { role: 'Solutions Architect', count: 2 },
      { role: 'Customer Success Manager', count: 2 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 26',
        title: 'Low-code platform enterprise features review',
        time: '2:00 PM - 3:00 PM',
        attendees: [
          { name: 'Thomas Wilson', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'NOV 12',
        title: 'Fortune 500 success stories & use cases',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Thomas Wilson', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-015',
    name: 'arc',
    domain: 'arc.dev',
    icon_color: 'bg-pink-500',
    last_meeting: '2024-08-20',
    next_meeting: '2024-12-18',
    customer_profile: 'Health Tech Growth-Stage Partnership-Ready',
    employee_count: '201-500',
    est_revenue: '$25M-$50M',
    summary: 'Telehealth platform connecting patients with specialists for rare and complex conditions. Operating in 25 states with 1,000+ partnered physicians. Series B funding in progress.',
    company_overview: 'Arc solves a critical healthcare access problem: rare disease diagnosis and specialist consultation. By leveraging telehealth technology and building relationships with leading specialists, they\'ve created a platform that dramatically reduces time-to-diagnosis for patients with complex conditions. Their patient-centric approach and partnerships with rare disease advocacy organizations have built a loyal, engaged user base.\n\nExpansion to 25 states with 1,000+ partnered physicians demonstrates strong provider adoption and validated business model. Recent Series A funding provides capital to scale operations and expand specialist networks. As healthcare continues to shift toward virtual delivery and personalized care, Arc\'s specialized focus on rare diseases positions them uniquely within the broader telehealth market. Their deep relationships with both patients and specialists create network effects that will be difficult for larger competitors to replicate.',
    product_offering: [
      'Telehealth platform for rare disease specialists',
      'Virtual consultations and patient management',
      'Electronic health record integration',
      'Insurance verification and billing',
      'Rare disease information and community support',
    ],
    recent_news: [
      { date: 'Jan 24, 2026', title: 'Expanded to 25 states with 1,000+ specialist physicians', source: 'https://www.arc.dev/press/expansion' },
      { date: 'Jan 3, 2026', title: 'Received $30M Series A funding', source: 'https://crunchbase.com/organization/arc-telehealth' },
      { date: 'Dec 15, 2025', title: 'Partnered with leading rare disease organizations', source: 'https://www.arc.dev/partnerships' },
    ],
    total_funding_raised: '$38M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$30M',
    latest_funding_date: 'Jan 3, 2026',
    deal: 'Deal with arc',
    deal_momentum: 'Stalled',
    primary_contact: 'Laura Garcia',
    primary_contact_color: 'red-500',
    linkedin_url: 'https://www.linkedin.com/company/arc-telehealth',
    industry: 'Outpatient care centers',
    company_type: 'Government',
    location: 'Austin, Texas, United States',
    tech_stack: 'React, Python, Django, PostgreSQL, HIPAA compliance, AWS',
    hiring_signals: [
      { role: 'Telehealth Specialist', count: 3 },
      { role: 'Python Developer', count: 2 },
      { role: 'Healthcare Compliance Officer', count: 1 },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 18',
        title: 'Rare disease specialist network expansion',
        time: '3:00 PM - 4:00 PM',
        attendees: [
          { name: 'Laura Garcia', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
        ],
      },
    ],
    past_meetings: [
      {
        date: 'AUG 20',
        title: 'Initial telehealth platform assessment',
        time: '1:00 PM - 2:30 PM',
        attendees: [
          { name: 'Laura Garcia', contact_role: 'buyer' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
  },
];
