import { Company } from '@/components/CompaniesPage';
import type { ContactCardData } from '@/types';

export const companiesData: Company[] = [
  {
    id: 'comp-001',
    name: 'actandacre',
    domain: 'actandacre.com',
    icon_color: 'bg-slate-600',
    last_meeting: '2024-12-01',
    next_meeting: '2024-12-15',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '201-500',
    est_revenue: '$50M-$100M',
    summary: 'Leading sustainable fashion e-commerce platform founded in 2019. They focus on eco-friendly materials and ethical production practices. Strong growth trajectory with 45% YoY increase in revenue.',
    recent_news: [
      { date: 'Feb 10, 2026', title: 'Announced expansion into European markets', source: 'https://techcrunch.com/actandacre-europe' },
      { date: 'Jan 15, 2026', title: 'Secured Series B funding of $25M', source: 'https://crunchbase.com/organization/actandacre' },
      { date: 'Dec 22, 2025', title: 'Launched new sustainable packaging initiative', source: 'https://www.sustainablefashionmag.com/actandacre' },
    ],
    total_funding_raised: '$45M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$25M',
    deal: 'Deal with actandacre',
    deal_momentum: 'Strong',
    primary_contact: 'Sarah Chen',
    primary_contact_color: 'blue-400',
    linkedin_url: 'https://www.linkedin.com/company/actandacre',
    industry: 'Apparel manufacturing',
    company_type: 'Private',
    location: 'Portland, Oregon, United States',
    tech_stack: 'React, Node.js, PostgreSQL, AWS, Stripe, Shopify',
    hiring_signals: [
      { role: 'Software Engineer', count: 3 },
      { role: 'Product Manager', count: 1 },
      { role: 'Supply Chain Analyst', count: 2 },
    ],
    contacts: [
      {
        name: 'Sarah Chen',
        email: 'sarah.chen@actandacre.com',
        job_title: 'Chief Operating Officer',
        avatar_color: 'blue-400',
        persona: 'Finance/Operations Executive',
        role_in_buying_process: 'Champion',
      },
      {
        name: 'Michael Rodriguez',
        email: 'michael.rodriguez@actandacre.com',
        job_title: 'VP of Supply Chain',
        avatar_color: 'green-500',
        persona: 'Technical Implementation Lead',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 15',
        title: 'Product demo & feature roadmap',
        time: '2:00 PM - 2:45 PM',
        attendees: [
          { name: 'Sarah Chen', contact_role: 'buyer' },
          { name: 'Michael Rodriguez', contact_role: 'buyer' },
          { name: 'Alex Rivera', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-002',
    name: 'adaptive sound technologies, inc.',
    domain: 'asoundtech.com',
    icon_color: 'bg-purple-400',
    last_meeting: '2024-10-13',
    next_meeting: '2024-12-20',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$10M-$25M',
    summary: 'Innovator in adaptive audio technology for wellness applications. Serves over 50,000 health practitioners nationwide. Expanding distribution through retail partnerships.',
    recent_news: [
      { date: 'Feb 8, 2026', title: 'Partnered with major wellness retailer for nationwide distribution', source: 'https://wellnessnews.com/adaptive-sound-partnership' },
      { date: 'Jan 20, 2026', title: 'Launched new audio profiles for meditation and sleep', source: 'https://www.asoundtech.com/press/new-profiles' },
    ],
    total_funding_raised: '$12M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$12M',
    deal: 'Deal with adaptive sound technologies, inc.',
    deal_momentum: 'Stalled',
    primary_contact: 'James Miller',
    primary_contact_color: 'purple-400',
    linkedin_url: 'https://www.linkedin.com/company/adaptive-sound-technologies',
    industry: 'Audio and video equipment manufacturing',
    company_type: 'Private',
    location: 'San Francisco, California, United States',
    tech_stack: 'Python, Django, React, WebRTC, TensorFlow, AWS',
    hiring_signals: [
      { role: 'Audio Engineer', count: 2 },
      { role: 'Machine Learning Engineer', count: 1 },
    ],
    contacts: [
      {
        name: 'James Miller',
        email: 'james.miller@asoundtech.com',
        job_title: 'Chief Technology Officer',
        avatar_color: 'purple-400',
        persona: 'Technical Founder/Decision Maker',
        role_in_buying_process: 'Economic Buyer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 20',
        title: 'Technical architecture review',
        time: '3:00 PM - 3:30 PM',
        attendees: [
          { name: 'James Miller', contact_role: 'buyer' },
          { name: 'Sarah Johnson', contact_role: 'seller' },
          { name: 'Marcus Chen', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-003',
    name: 'adco medical suppliers',
    domain: 'adcopros.com',
    icon_color: 'bg-blue-500',
    last_meeting: '2024-09-19',
    next_meeting: '2024-12-18',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '201-500',
    est_revenue: '$100M-$250M',
    summary: 'Established medical supply distributor serving 200+ clinics and healthcare facilities. Known for reliable logistics and competitive pricing. Currently modernizing their operations.',
    recent_news: [
      { date: 'Feb 5, 2026', title: 'Upgraded warehouse automation systems', source: 'https://supplychaintoday.com/adco-automation' },
      { date: 'Jan 12, 2026', title: 'Expanded service coverage to 3 new states', source: 'https://www.adcopros.com/expansion-announcement' },
      { date: 'Dec 18, 2025', title: 'Achieved ISO 13485 Medical Device Quality certification', source: 'https://medicalsupplyjournal.com/adco-iso-cert' },
    ],
    total_funding_raised: '$85M',
    num_funding_rounds: 3,
    latest_funding_stage: 'Series C',
    latest_funding_round: '$40M',
    deal: 'Deal with adco medical suppliers',
    deal_momentum: 'At risk',
    primary_contact: 'Emily Davis',
    primary_contact_color: 'green-400',
    linkedin_url: 'https://www.linkedin.com/company/adco-medical-suppliers',
    industry: 'Medical equipment manufacturing',
    company_type: 'Private',
    location: 'Boston, Massachusetts, United States',
    tech_stack: 'Java, Spring Boot, Oracle Database, Azure, SAP',
    hiring_signals: [
      { role: 'Warehouse Manager', count: 4 },
      { role: 'Java Developer', count: 2 },
      { role: 'Business Analyst', count: 1 },
    ],
    contacts: [
      {
        name: 'Emily Davis',
        email: 'emily.davis@adcopros.com',
        job_title: 'Director of Procurement',
        avatar_color: 'green-400',
        persona: 'Operations/Implementation Manager',
        role_in_buying_process: 'Champion',
      },
      {
        name: 'Robert Thompson',
        email: 'robert.thompson@adcopros.com',
        job_title: 'Logistics Manager',
        avatar_color: 'blue-500',
        persona: 'Operations/Implementation Manager',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 18',
        title: 'Implementation planning session',
        time: '1:00 PM - 2:00 PM',
        attendees: [
          { name: 'Emily Davis', contact_role: 'buyer' },
          { name: 'Robert Thompson', contact_role: 'buyer' },
          { name: 'David Kim', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-004',
    name: 'advocare',
    domain: 'advocare.com',
    icon_color: 'bg-blue-600',
    last_meeting: '2024-11-18',
    next_meeting: '2024-12-22',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '1001-5000',
    est_revenue: '$1B-$10B',
    summary: 'Global nutrition and wellness company with presence in 30+ countries. Operating multi-channel sales including direct, retail, and professional channels. Seeking operational efficiency improvements.',
    recent_news: [
      { date: 'Feb 12, 2026', title: 'Launched new product line in 15 countries', source: 'https://www.advocare.com/press/new-product-launch' },
      { date: 'Jan 28, 2026', title: 'Announced strategic partnership with global fitness chain', source: 'https://fitnessinsider.com/advocare-partnership' },
      { date: 'Jan 5, 2026', title: 'Reported Q4 revenue growth of 18% YoY', source: 'https://finance.yahoo.com/quote/ADVOCARE' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2018',
    deal: 'Deal with advocare',
    deal_momentum: 'Strong',
    primary_contact: 'Alex Johnson',
    primary_contact_color: 'pink-400',
    linkedin_url: 'https://www.linkedin.com/company/advocare',
    industry: 'Beverage manufacturing',
    company_type: 'Public',
    location: 'Houston, Texas, United States',
    tech_stack: 'C#, .NET, SQL Server, Azure, Salesforce, Tableau',
    hiring_signals: [
      { role: 'Sales Executive', count: 5 },
      { role: 'Supply Chain Specialist', count: 3 },
      { role: '.NET Developer', count: 2 },
    ],
    contacts: [
      {
        name: 'Alex Johnson',
        email: 'alex.johnson@advocare.com',
        job_title: 'VP of Operations',
        avatar_color: 'pink-400',
        persona: 'Finance/Operations Executive',
        role_in_buying_process: 'Economic Buyer',
      },
      {
        name: 'Jennifer Lee',
        email: 'jennifer.lee@advocare.com',
        job_title: 'Senior Manager, Product Development',
        avatar_color: 'amber-400',
        persona: 'Marketing/Growth Leader',
        role_in_buying_process: 'Influencer',
      },
    ],
    upcoming_meetings: [
      {
        date: 'DEC 22',
        title: 'Executive steering committee',
        time: '10:00 AM - 11:00 AM',
        attendees: [
          { name: 'Alex Johnson', contact_role: 'buyer' },
          { name: 'Jennifer Lee', contact_role: 'buyer' },
          { name: 'Patricia Williams', contact_role: 'seller' },
        ],
      },
    ],
  },
  {
    id: 'comp-005',
    name: 'adyen',
    domain: 'adyen.com',
    icon_color: 'bg-green-500',
    last_meeting: '2024-11-20',
    next_meeting: '2024-12-25',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '5001-10000',
    est_revenue: '$10B+',
    summary: 'Leading fintech payment processor handling $500B+ in annual transaction volume. Serves 5,000+ enterprise customers globally. Continuously expanding platform capabilities.',
    recent_news: [
      { date: 'Feb 14, 2026', title: 'Introduced AI-powered fraud detection system', source: 'https://www.adyen.com/blog/ai-fraud-detection' },
      { date: 'Jan 30, 2026', title: 'Expanded coverage to 195 countries and territories', source: 'https://finance.yahoo.com/quote/ADYEN' },
      { date: 'Jan 8, 2026', title: 'Achieved $1 trillion cumulative transaction milestone', source: 'https://www.adyen.com/press/trillion-milestone' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2018',
    deal: 'Deal with adyen',
    deal_momentum: 'Active',
    primary_contact: 'Maria Lopez',
    primary_contact_color: 'amber-400',
    linkedin_url: 'https://www.linkedin.com/company/adyen',
    industry: 'Financial services',
    company_type: 'Public',
    location: 'Amsterdam, North Holland, Netherlands',
    tech_stack: 'Go, Kotlin, PostgreSQL, AWS, Kubernetes, Grafana',
    hiring_signals: [
      { role: 'Backend Engineer', count: 6 },
      { role: 'Security Engineer', count: 3 },
      { role: 'DevOps Engineer', count: 2 },
    ],
    contacts: [
      {
        name: 'Maria Lopez',
        email: 'maria.lopez@adyen.com',
        job_title: 'Head of Enterprise Solutions',
        avatar_color: 'amber-400',
        persona: 'Technical Founder/Decision Maker',
        role_in_buying_process: 'Economic Buyer',
      },
    ],
  },
  {
    id: 'comp-006',
    name: 'aletha health',
    domain: 'alethahealth.com',
    icon_color: 'bg-gray-700',
    last_meeting: '2024-09-25',
    next_meeting: '2024-12-19',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$5M-$10M',
    summary: 'Digital health platform providing personalized wellness programs. Partnered with 15 major employers for employee health initiatives. Growing user base of 75,000+.',
    recent_news: [
      { date: 'Feb 3, 2026', title: 'Partnered with 3 Fortune 500 companies', source: 'https://www.alethahealth.com/press/fortune500-partnerships' },
      { date: 'Jan 10, 2026', title: 'Launched mobile app v2.0 with AI coaching', source: 'https://apps.apple.com/us/app/aletha-health/id123456789' },
    ],
    total_funding_raised: '$8M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$5M',
    deal: 'Deal with aletha health',
    deal_momentum: 'Strong',
    primary_contact: 'David Park',
    primary_contact_color: 'red-400',
    linkedin_url: 'https://www.linkedin.com/company/aletha-health',
    industry: 'Outpatient care centers',
    company_type: 'Nonprofit',
    location: 'Denver, Colorado, United States',
    tech_stack: 'React Native, Firebase, Python, TensorFlow, HIPAA compliance',
    hiring_signals: [
      { role: 'Mobile Developer', count: 2 },
      { role: 'Health Coach', count: 4 },
      { role: 'Data Scientist', count: 1 },
    ],
  },
  {
    id: 'comp-007',
    name: 'allermi',
    domain: 'allermi.com',
    icon_color: 'bg-gray-500',
    last_meeting: '2024-09-19',
    next_meeting: '2024-12-16',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '201-500',
    est_revenue: '$25M-$50M',
    summary: 'Specialty allergen-free personal care brand disrupting the beauty space. DTC-focused with strong social media presence. Projected 60% revenue growth this year.',
    recent_news: [
      { date: 'Feb 6, 2026', title: 'Reached 1M social media followers milestone', source: 'https://www.instagram.com/allermi_beauty/' },
      { date: 'Jan 22, 2026', title: 'Launched in 200+ retail locations nationwide', source: 'https://www.allermi.com/retail-locations' },
      { date: 'Dec 28, 2025', title: 'Featured in major beauty magazine', source: 'https://www.beautyindustrymagazine.com/allermi-feature' },
    ],
    total_funding_raised: '$32M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$18M',
    deal: 'Deal with allermi',
    deal_momentum: 'Closed',
    primary_contact: 'Jessica Wong',
    primary_contact_color: 'cyan-400',
    linkedin_url: 'https://www.linkedin.com/company/allermi',
    industry: 'Personal care product manufacturing',
    company_type: 'Private',
    location: 'Los Angeles, California, United States',
    tech_stack: 'Vue.js, Express.js, MongoDB, AWS Lambda, Klaviyo, Shopify Plus',
    hiring_signals: [
      { role: 'Marketing Manager', count: 2 },
      { role: 'Brand Designer', count: 1 },
      { role: 'Content Creator', count: 3 },
    ],
  },
  {
    id: 'comp-008',
    name: 'alma',
    domain: 'alma.food',
    icon_color: 'bg-green-400',
    last_meeting: '2024-10-21',
    next_meeting: '2024-12-17',
    customer_profile: 'SMB DTC Health/Wellness Fast-Movers',
    employee_count: '11-50',
    est_revenue: '$1M-$10M',
    summary: 'Organic plant-based food company founded in 2018. Direct-to-consumer model with growing wholesale partnerships. Expanding product line across 12 US states.',
    recent_news: [
      { date: 'Feb 1, 2026', title: 'Expanded product line with 5 new plant-based options', source: 'https://www.alma.food/new-products' },
      { date: 'Jan 14, 2026', title: 'Secured partnership with major organic retailer chain', source: 'https://organicfoodinsider.com/alma-retail-partnership' },
    ],
    total_funding_raised: '$4.5M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Seed',
    latest_funding_round: '$4.5M',
    deal: 'Deal with alma',
    deal_momentum: 'Active',
    primary_contact: 'Michael Chen',
    primary_contact_color: 'indigo-400',
    linkedin_url: 'https://www.linkedin.com/company/alma-organic-food',
    industry: 'Food and beverage manufacturing',
    company_type: 'Private',
    location: 'Berlin, Berlin, Germany',
    tech_stack: 'Next.js, TypeScript, Supabase, Stripe, SendGrid, GCP',
    hiring_signals: [
      { role: 'Operations Manager', count: 1 },
      { role: 'Product Designer', count: 1 },
      { role: 'Full Stack Developer', count: 2 },
    ],
  },
  {
    id: 'comp-009',
    name: 'alyze.health',
    domain: 'alyze.health',
    icon_color: 'bg-purple-300',
    last_meeting: '2024-11-26',
    next_meeting: '2024-12-21',
    customer_profile: 'Health Tech Growth-Stage Partnership-Ready',
    employee_count: '201-500',
    est_revenue: '$10M-$25M',
    summary: 'AI-powered health analytics platform for predictive diagnostics. Recently secured Series A funding. Partnering with 8 healthcare systems in pilot programs.',
    recent_news: [
      { date: 'Feb 11, 2026', title: 'Secured $15M Series A funding round', source: 'https://crunchbase.com/organization/alyze-health' },
      { date: 'Jan 26, 2026', title: 'Expanded pilot programs to 8 healthcare systems', source: 'https://www.alyze.health/press/pilot-expansion' },
      { date: 'Jan 2, 2026', title: 'Published research in peer-reviewed medical journal', source: 'https://www.pubmed.gov/alyze-research' },
    ],
    total_funding_raised: '$15M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$15M',
    deal: 'Deal with alyze.health',
    deal_momentum: 'Strong',
    primary_contact: 'Rachel Martinez',
    primary_contact_color: 'orange-400',
    linkedin_url: 'https://www.linkedin.com/company/alyze-health',
    industry: 'Biotechnology research',
    company_type: 'Educational',
    location: 'Cambridge, Cambridgeshire, United Kingdom',
    tech_stack: 'Python, PyTorch, FastAPI, PostgreSQL, Docker, Kubernetes, GCP',
    hiring_signals: [
      { role: 'Data Scientist', count: 3 },
      { role: 'Clinical Researcher', count: 2 },
      { role: 'Healthcare Solutions Architect', count: 1 },
    ],
  },
  {
    id: 'comp-010',
    name: 'andiemup',
    domain: 'andiemup.com',
    icon_color: 'bg-gray-800',
    last_meeting: '2024-12-08',
    next_meeting: '2024-12-23',
    customer_profile: 'Mid-Market Multi-Channel Operators',
    employee_count: '201-500',
    est_revenue: '$250M-$500M',
    summary: 'Omnichannel retail platform connecting 300+ independent brands. Operates both B2B2C marketplace and white-label solutions. Processing $20M+ in monthly transactions.',
    recent_news: [
      { date: 'Feb 7, 2026', title: 'Onboarded 50 new independent brands', source: 'https://www.andiemup.com/press/brand-onboarding' },
      { date: 'Jan 19, 2026', title: 'Launched white-label solution for enterprise partners', source: 'https://www.andiemup.com/enterprise' },
      { date: 'Dec 28, 2025', title: 'Hit $20M monthly transaction volume milestone', source: 'https://techcrunch.com/andiemup-milestone' },
    ],
    total_funding_raised: '$120M',
    num_funding_rounds: 4,
    latest_funding_stage: 'Series C',
    latest_funding_round: '$60M',
    deal: 'Deal with andiemup',
    deal_momentum: 'Active',
    primary_contact: 'Kevin Thompson',
    primary_contact_color: 'blue-500',
    linkedin_url: 'https://www.linkedin.com/company/andiemup',
    industry: 'Retail',
    company_type: 'Public_Subsidiary',
    location: 'New York, New York, United States',
    tech_stack: 'React, Node.js, MySQL, Redis, AWS, Elasticsearch, Datadog',
    hiring_signals: [
      { role: 'Frontend Engineer', count: 4 },
      { role: 'Backend Engineer', count: 3 },
      { role: 'QA Engineer', count: 2 },
    ],
  },
  {
    id: 'comp-011',
    name: 'anker',
    domain: 'anker.com',
    icon_color: 'bg-blue-400',
    last_meeting: '2024-11-05',
    next_meeting: '2024-12-19',
    customer_profile: 'Mid-Market E-Commerce Growth Brands',
    employee_count: '1001-5000',
    est_revenue: '$500M-$1B',
    summary: 'Consumer electronics brand known for charging accessories and smart home products. Global reach with operations in 80+ countries. Selling through 5,000+ retail locations.',
    recent_news: [
      { date: 'Feb 9, 2026', title: 'Launched new smart home ecosystem with 12 products', source: 'https://www.anker.com/press/smart-home-launch' },
      { date: 'Jan 16, 2026', title: 'Expanded into 15 new markets in Asia-Pacific', source: 'https://techasia.com/anker-expansion' },
      { date: 'Dec 20, 2025', title: 'Achieved record Q4 revenue of $500M', source: 'https://finance.yahoo.com/quote/ANKER' },
    ],
    total_funding_raised: 'Public company',
    num_funding_rounds: 0,
    latest_funding_stage: 'Public',
    latest_funding_round: 'IPO - 2021',
    deal: 'Deal with anker',
    deal_momentum: 'Strong',
    primary_contact: 'Sophie Anderson',
    primary_contact_color: 'green-500',
    linkedin_url: 'https://www.linkedin.com/company/anker',
    industry: 'Computer hardware manufacturing',
    company_type: 'Public',
    location: 'Shenzhen, Guangdong, China',
    tech_stack: 'Flutter, Dart, Java, Go, AWS, Kubernetes, Jenkins',
    hiring_signals: [
      { role: 'Product Engineer', count: 5 },
      { role: 'Supply Chain Manager', count: 2 },
      { role: 'Sales Engineer', count: 3 },
    ],
  },
  {
    id: 'comp-012',
    name: 'anthropic',
    domain: 'anthropic.com',
    icon_color: 'bg-orange-500',
    last_meeting: '2024-10-15',
    next_meeting: '2024-12-24',
    customer_profile: 'Enterprise AI/ML',
    employee_count: '201-500',
    est_revenue: '$100M-$250M',
    summary: 'Leading AI research company specializing in large language models. Serving 500+ enterprise customers with Claude AI platform. Growing $100M+ in annual revenue.',
    recent_news: [
      { date: 'Feb 13, 2026', title: 'Released Claude 4 with enhanced reasoning capabilities', source: 'https://www.anthropic.com/news/claude-4' },
      { date: 'Jan 29, 2026', title: 'Announced $1B funding round at $20B valuation', source: 'https://techcrunch.com/anthropic-funding' },
      { date: 'Jan 8, 2026', title: 'Crossed 500+ enterprise customers milestone', source: 'https://www.anthropic.com/blog/enterprise-milestone' },
    ],
    total_funding_raised: '$5.3B',
    num_funding_rounds: 5,
    latest_funding_stage: 'Series D',
    latest_funding_round: '$1B',
    deal: 'Deal with anthropic',
    deal_momentum: 'Strong',
    primary_contact: 'Christopher Lee',
    primary_contact_color: 'purple-500',
    linkedin_url: 'https://www.linkedin.com/company/anthropic',
    industry: 'Biotechnology research',
    company_type: 'Private',
    location: 'San Francisco, California, United States',
    tech_stack: 'Python, JAX, CUDA, Cloud TPU, Slack API, Figma',
    hiring_signals: [
      { role: 'AI Research Engineer', count: 4 },
      { role: 'ML Engineer', count: 3 },
      { role: 'Systems Engineer', count: 2 },
    ],
  },
  {
    id: 'comp-013',
    name: 'appflowy',
    domain: 'appflowy.io',
    icon_color: 'bg-indigo-600',
    last_meeting: '2024-09-30',
    next_meeting: '2024-12-20',
    customer_profile: 'SMB Productivity',
    employee_count: '201-500',
    est_revenue: '$5M-$10M',
    summary: 'Open-source productivity platform competing with Notion and Airtable. Self-hosted and cloud options available. Growing community of 50,000+ active users.',
    recent_news: [
      { date: 'Feb 1, 2026', title: 'Reached 50,000 active users in open-source community', source: 'https://github.com/AppFlowy/AppFlowy' },
      { date: 'Jan 10, 2026', title: 'Launched AppFlowy Cloud with enterprise features', source: 'https://appflowy.io/blog/cloud-launch' },
    ],
    total_funding_raised: '$3.2M',
    num_funding_rounds: 1,
    latest_funding_stage: 'Seed',
    latest_funding_round: '$3.2M',
    deal: 'Deal with appflowy',
    deal_momentum: 'Active',
    primary_contact: 'Nicole Brown',
    primary_contact_color: 'pink-500',
    linkedin_url: 'https://www.linkedin.com/company/appflowy',
    industry: 'Software development',
    company_type: 'Private',
    location: 'Singapore, Singapore, Singapore',
    tech_stack: 'Rust, Flutter, Firebase, PostgreSQL, WebAssembly, Self-hosted',
    hiring_signals: [
      { role: 'Rust Developer', count: 2 },
      { role: 'Community Manager', count: 1 },
      { role: 'Product Manager', count: 1 },
    ],
  },
  {
    id: 'comp-014',
    name: 'appsmith',
    domain: 'appsmith.com',
    icon_color: 'bg-green-600',
    last_meeting: '2024-11-12',
    next_meeting: '2024-12-26',
    customer_profile: 'Enterprise Multi-Channel Advanced Operations',
    employee_count: '201-500',
    est_revenue: '$50M-$100M',
    summary: 'Low-code internal tools platform enabling enterprises to build apps 10x faster. Adopted by 200+ Fortune 500 companies. Providing solutions for data-heavy workflows.',
    recent_news: [
      { date: 'Feb 14, 2026', title: 'Announced enterprise security features with SOC 2 certification', source: 'https://www.appsmith.com/blog/soc2-certification' },
      { date: 'Jan 23, 2026', title: 'Adopted by 200+ Fortune 500 companies', source: 'https://www.appsmith.com/customers' },
      { date: 'Jan 1, 2026', title: 'Raised $45M Series B funding', source: 'https://crunchbase.com/organization/appsmith' },
    ],
    total_funding_raised: '$59M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series B',
    latest_funding_round: '$45M',
    deal: 'Deal with appsmith',
    deal_momentum: 'Strong',
    primary_contact: 'Thomas Wilson',
    primary_contact_color: 'amber-500',
    linkedin_url: 'https://www.linkedin.com/company/appsmith',
    industry: 'Software development',
    company_type: 'Private',
    location: 'Toronto, Ontario, Canada',
    tech_stack: 'React, Node.js, MongoDB, TypeScript, Docker, AWS Lambda',
    hiring_signals: [
      { role: 'Full Stack Developer', count: 3 },
      { role: 'Solutions Architect', count: 2 },
      { role: 'Customer Success Manager', count: 2 },
    ],
  },
  {
    id: 'comp-015',
    name: 'arc',
    domain: 'arc.dev',
    icon_color: 'bg-pink-500',
    last_meeting: '2024-08-20',
    next_meeting: '2024-12-18',
    customer_profile: 'Health Tech Growth-Stage Partnership-Ready',
    employee_count: '201-500',
    est_revenue: '$25M-$50M',
    summary: 'Telehealth platform connecting patients with specialists for rare and complex conditions. Operating in 25 states with 1,000+ partnered physicians. Series B funding in progress.',
    recent_news: [
      { date: 'Jan 24, 2026', title: 'Expanded to 25 states with 1,000+ specialist physicians', source: 'https://www.arc.dev/press/expansion' },
      { date: 'Jan 3, 2026', title: 'Received $30M Series A funding', source: 'https://crunchbase.com/organization/arc-telehealth' },
      { date: 'Dec 15, 2025', title: 'Partnered with leading rare disease organizations', source: 'https://www.arc.dev/partnerships' },
    ],
    total_funding_raised: '$38M',
    num_funding_rounds: 2,
    latest_funding_stage: 'Series A',
    latest_funding_round: '$30M',
    deal: 'Deal with arc',
    deal_momentum: 'Stalled',
    primary_contact: 'Laura Garcia',
    primary_contact_color: 'red-500',
    linkedin_url: 'https://www.linkedin.com/company/arc-telehealth',
    industry: 'Outpatient care centers',
    company_type: 'Government',
    location: 'Austin, Texas, United States',
    tech_stack: 'React, Python, Django, PostgreSQL, HIPAA compliance, AWS',
    hiring_signals: [
      { role: 'Telehealth Specialist', count: 3 },
      { role: 'Python Developer', count: 2 },
      { role: 'Healthcare Compliance Officer', count: 1 },
    ],
  },
];
