import { Contact } from '@/components/ContactsPage';

export const contactsData: Contact[] = [
  {
    id: 'contact-001',
    name: '/vilanova/',
    email: 'mike.vilanova@equinox.com',
    last_meeting: '2024-11-24',
    buyer_persona: null,
  },
  {
    id: 'contact-002',
    name: 'Aasiyah Abdulsalam',
    email: 'aasiyah@therenatural.com',
    last_meeting: '2024-11-07',
    buyer_persona: null,
  },
  {
    id: 'contact-003',
    name: 'Abate, Jessica',
    email: 'jabate@sac.shiseido.com',
    last_meeting: '2024-09-11',
    buyer_persona: null,
  },
  {
    id: 'contact-004',
    name: 'Abbas Ajmeri',
    email: 'abbas@medicaleshop.com',
    last_meeting: '2024-10-06',
    buyer_persona: null,
  },
  {
    id: 'contact-005',
    name: 'Abby Armijo',
    email: 'aarmijo@adcopros.com',
    last_meeting: '2024-09-19',
    buyer_persona: 'Technical Founder/Decision Maker',
  },
  {
    id: 'contact-006',
    name: 'Abby Burke',
    email: 'abby.burke@underdogteam.com',
    last_meeting: '2024-12-02',
    buyer_persona: null,
  },
  {
    id: 'contact-007',
    name: 'Abigail Miller',
    email: 'abigail@myfirmtech.com',
    last_meeting: '2024-11-14',
    buyer_persona: null,
  },
  {
    id: 'contact-008',
    name: 'Adam DYER',
    email: 'adam.dyer@loreal.com',
    last_meeting: '2024-12-12',
    buyer_persona: 'Marketing/Growth Leader',
  },
  {
    id: 'contact-009',
    name: 'Ádám Nagyházy-Horváth',
    email: 'nagyhazy-horvath@biotia.io',
    last_meeting: '2024-10-06',
    buyer_persona: null,
  },
  {
    id: 'contact-010',
    name: 'Adan from Studio 31',
    email: 'hello@studio31.io',
    last_meeting: '2024-11-12',
    buyer_persona: null,
  },
  {
    id: 'contact-011',
    name: 'Adria Aparisi',
    email: 'adria.aparisi@isdin.com',
    last_meeting: '2024-12-18',
    buyer_persona: null,
  },
  {
    id: 'contact-012',
    name: 'Adrian Schmidt',
    email: 'adrian@techventure.com',
    last_meeting: '2024-09-30',
    buyer_persona: null,
  },
  {
    id: 'contact-013',
    name: 'Adriana Gomez',
    email: 'adriana.gomez@innovations.com',
    last_meeting: '2024-11-20',
    buyer_persona: null,
  },
  {
    id: 'contact-014',
    name: 'Aeron Mills',
    email: 'aeron@marketingplus.com',
    last_meeting: '2024-10-15',
    buyer_persona: null,
  },
  {
    id: 'contact-015',
    name: 'Agatha Ford',
    email: 'agatha.ford@enterprise.com',
    last_meeting: '2024-12-08',
    buyer_persona: null,
  },
  {
    id: 'contact-016',
    name: 'Agatha Williams',
    email: 'agatha.williams@solutions.io',
    last_meeting: '2024-11-01',
    buyer_persona: null,
  },
  {
    id: 'contact-017',
    name: 'Aggie Patterson',
    email: 'aggie.p@growthco.com',
    last_meeting: '2024-10-28',
    buyer_persona: null,
  },
  {
    id: 'contact-018',
    name: 'Agnes Chen',
    email: 'agnes.chen@techcorp.com',
    last_meeting: '2024-11-05',
    buyer_persona: null,
  },
];
