import { Contact } from '@/components/ContactsPage';

export const contactsData: Contact[] = [
  {
    id: 'contact-001',
    name: 'Mike Vilanova',
    email: 'mike.vilanova@equinox.com',
    last_meeting: '2024-11-24',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Equinox',
    job_title: 'VP of Operations',
    location: 'New York, New York, United States',
    activity_summary: 'Last spoke with them on November 24, 2024 on a discovery call about their operational challenges.',
    next_meeting: '2024-12-15',
    personal_markers: ['Huge NY Giants fan', 'Just got back from Miami trip', 'Mentioned wanting to learn golf'],
    linkedin_url: 'https://linkedin.com/in/mike-vilanova-12345',
    associated_deals: [{ name: 'Equinox Operations Platform', momentum: 'Strong' }],
  },
  {
    id: 'contact-002',
    name: 'Aasiyah Abdulsalam',
    email: 'aasiyah@therenatural.com',
    last_meeting: '2024-11-07',
    buyer_persona: 'Technical Implementation Lead',
    company: 'The Natural',
    job_title: 'Senior Technical Lead',
    location: 'San Francisco, California, United States',
    activity_summary: 'Last spoke with them on November 7, 2024 during a technical deep dive to understand their integration requirements.',
    next_meeting: null,
    personal_markers: ['Basketball enthusiast - supports Warriors', 'Recently promoted to senior engineer role', 'Has a passion for outdoor hiking'],
    linkedin_url: 'https://linkedin.com/in/aasiyah-abdulsalam-98765',
    associated_deals: [{ name: 'The Natural Integration Suite', momentum: 'At risk' }],
  },
  {
    id: 'contact-003',
    name: 'Jessica Abate',
    email: 'jabate@sac.shiseido.com',
    last_meeting: '2024-09-11',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Shiseido',
    job_title: 'Director of Finance',
    location: 'Tokyo, Tokyo, Japan',
    activity_summary: 'Last spoke with them on September 11, 2024 regarding budget alignment and ROI projections for the new fiscal year.',
    next_meeting: '2024-12-20',
    personal_markers: ['Avid reader - loves mystery novels', 'Just celebrated 15 years at Shiseido', 'Mentioned upcoming wedding in Japan'],
    linkedin_url: 'https://linkedin.com/in/jessica-abate-54321',
  },
  {
    id: 'contact-004',
    name: 'Abbas Ajmeri',
    email: 'abbas@medicaleshop.com',
    last_meeting: '2024-10-06',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'Medical eShop',
    job_title: 'Head of Growth Marketing',
    location: 'Dubai, Dubai, United Arab Emirates',
    activity_summary: 'Last spoke with them on October 6, 2024 to discuss growth strategies and market expansion opportunities.',
    next_meeting: null,
    personal_markers: ['Soccer fan - supports Manchester United', 'Recently became a father', 'Learning to cook Middle Eastern cuisine'],
    linkedin_url: 'https://linkedin.com/in/abbas-ajmeri-76543',
  },
  {
    id: 'contact-005',
    name: 'Abby Armijo',
    email: 'aarmijo@adcopros.com',
    last_meeting: '2024-09-19',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'ADCO Pros',
    job_title: 'Co-Founder & CTO',
    location: 'Austin, Texas, United States',
    activity_summary: 'Last spoke with them on September 19, 2024 about technical architecture and implementation roadmap for their platform.',
    next_meeting: '2024-12-10',
    personal_markers: ['Tennis player - plays weekly matches', 'Recently launched podcast about startups', 'Dog lover - has two golden retrievers'],
    linkedin_url: 'https://linkedin.com/in/abby-armijo-11111',
    associated_deals: [{ name: 'ADCO Pro Tools', momentum: 'Strong' }, { name: 'ADCO Analytics', momentum: 'Stalled' }],
  },
  {
    id: 'contact-006',
    name: 'Abby Burke',
    email: 'abby.burke@underdogteam.com',
    last_meeting: '2024-12-02',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Underdog',
    job_title: 'Finance Manager',
    location: 'Boston, Massachusetts, United States',
    activity_summary: 'Last spoke with them on December 2, 2024 to review Q4 financial results and discuss 2025 budget planning.',
    personal_markers: ['Boston Red Sox fan since childhood', 'Took a sabbatical last year to travel', 'Recently completed MBA in Finance'],
    linkedin_url: 'https://linkedin.com/in/abby-burke-22222',
  },
  {
    id: 'contact-007',
    name: 'Abigail Miller',
    email: 'abigail@myfirmtech.com',
    last_meeting: '2024-11-14',
    buyer_persona: 'Technical Implementation Lead',
    company: 'MyFirm Tech',
    job_title: 'Senior Implementation Engineer',
    location: 'Seattle, Washington, United States',
    activity_summary: 'Last spoke with them on November 14, 2024 during an implementation planning session for their new platform deployment.',
    personal_markers: ['Indie video game enthusiast', 'Recently moved to Seattle from Austin', 'Volunteers with local tech mentorship program'],
    linkedin_url: 'https://linkedin.com/in/abigail-miller-33333',
  },
  {
    id: 'contact-008',
    name: 'Adam DYER',
    email: 'adam.dyer@loreal.com',
    last_meeting: '2024-12-12',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'L\'Oreal',
    job_title: 'Director of Marketing',
    location: 'Paris, France',
    activity_summary: 'Last spoke with them on December 12, 2024 about digital marketing initiatives and expanding their brand presence across Europe.',
    personal_markers: ['Rugby fan - watches international matches', 'Fluent in 3 languages', 'Recently completed marathon in Paris'],
    linkedin_url: 'https://linkedin.com/in/adam-dyer-44444',
  },
  {
    id: 'contact-009',
    name: 'Ádám Nagyházy-Horváth',
    email: 'nagyhazy-horvath@biotia.io',
    last_meeting: '2024-10-06',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'Biotia',
    job_title: 'Co-Founder & CEO',
    location: 'Budapest, Hungary',
    activity_summary: 'Last spoke with them on October 6, 2024 regarding their biotech research funding and technical infrastructure needs.',
    personal_markers: ['Handball player - coaches local youth team', 'Recently visited family in Budapest', 'Passionate about biotech education'],
    linkedin_url: 'https://linkedin.com/in/adam-nagyhazy-horvath-55555',
  },
  {
    id: 'contact-010',
    name: 'Adan from Studio 31',
    email: 'hello@studio31.io',
    last_meeting: '2024-11-12',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Studio 31',
    job_title: 'Operations Director',
    location: 'Portland, Oregon, United States',
    activity_summary: 'Last spoke with them on November 12, 2024 to discuss operational efficiency improvements and workflow automation.',
    personal_markers: ['Photography hobbyist - does weekend shoots', 'Just bought a house in Portland', 'Collecting vinyl records'],
    linkedin_url: 'https://linkedin.com/in/adan-studio31-66666',
  },
  {
    id: 'contact-011',
    name: 'Adria Aparisi',
    email: 'adria.aparisi@isdin.com',
    last_meeting: '2024-12-18',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'ISDIN',
    job_title: 'Head of Digital Marketing',
    location: 'Barcelona, Spain',
    activity_summary: 'Last spoke with them on December 18, 2024 about digital product launches and customer engagement strategies for their skincare line.',
    personal_markers: ['Barcelona football fan since childhood', 'Just launched a wellness blog', 'Rock climbing enthusiast'],
    linkedin_url: 'https://linkedin.com/in/adria-aparisi-77777',
  },
  {
    id: 'contact-012',
    name: 'Adrian Schmidt',
    email: 'adrian@techventure.com',
    last_meeting: '2024-09-30',
    buyer_persona: 'Technical Implementation Lead',
    company: 'TechVenture',
    job_title: 'Head of Engineering',
    location: 'Berlin, Germany',
    activity_summary: 'Last spoke with them on September 30, 2024 about technical architecture decisions and cloud infrastructure optimization.',
    personal_markers: ['Cycling enthusiast - commutes by bike', 'Recently became a German citizen', 'Homebrewing beer as a hobby'],
    linkedin_url: 'https://linkedin.com/in/adrian-schmidt-88888',
  },
  {
    id: 'contact-013',
    name: 'Adriana Gomez',
    email: 'adriana.gomez@innovations.com',
    last_meeting: '2024-11-20',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Innovations Inc',
    job_title: 'Chief Financial Officer',
    location: 'Mexico City, Mexico',
    activity_summary: 'Last spoke with them on November 20, 2024 to review financial performance and discuss cost optimization initiatives.',
    personal_markers: ['Salsa dancer - competes at local level', 'Recently promoted to CFO', 'Mentors young women in finance'],
    linkedin_url: 'https://linkedin.com/in/adriana-gomez-99999',
  },
  {
    id: 'contact-014',
    name: 'Aeron Mills',
    email: 'aeron@marketingplus.com',
    last_meeting: '2024-10-15',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'Marketing Plus',
    job_title: 'Founder & CTO',
    location: 'Denver, Colorado, United States',
    activity_summary: 'Last spoke with them on October 15, 2024 regarding marketing automation platform development and customer analytics features.',
    personal_markers: ['Avid skier - goes to Colorado every winter', 'Fascinated by Japanese culture', 'Recently adopted a rescue dog'],
    linkedin_url: 'https://linkedin.com/in/aeron-mills-00001',
  },
  {
    id: 'contact-015',
    name: 'Agatha Ford',
    email: 'agatha.ford@enterprise.com',
    last_meeting: '2024-12-08',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Enterprise Corp',
    job_title: 'Operations Manager',
    location: 'Boston, Massachusetts, United States',
    activity_summary: 'Last spoke with them on December 8, 2024 to discuss supply chain optimization and process improvement initiatives.',
    personal_markers: ['Marathon runner - completed Boston Marathon', 'Plant parent - has a whole greenhouse', 'Gardening Instagram influencer'],
    linkedin_url: 'https://linkedin.com/in/agatha-ford-00002',
  },
  {
    id: 'contact-016',
    name: 'Agatha Williams',
    email: 'agatha.williams@solutions.io',
    last_meeting: '2024-11-01',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'Solutions.io',
    job_title: 'VP of Marketing',
    location: 'Austin, Texas, United States',
    activity_summary: 'Last spoke with them on November 1, 2024 about market positioning strategy and brand awareness campaigns.',
    personal_markers: ['Jazz music lover - plays saxophone', 'Recently traveled to Morocco', 'Vegan chef enthusiast'],
    linkedin_url: 'https://linkedin.com/in/agatha-williams-00003',
  },
  {
    id: 'contact-017',
    name: 'Aggie Patterson',
    email: 'aggie.p@growthco.com',
    last_meeting: '2024-10-28',
    buyer_persona: 'Technical Implementation Lead',
    company: 'GrowthCo',
    job_title: 'Senior Technical Lead',
    location: 'San Francisco, California, United States',
    activity_summary: 'Last spoke with them on October 28, 2024 during technical requirements gathering for their new system implementation.',
    personal_markers: ['Triathlon competitor - qualifying for nationals', 'Recently moved to San Francisco', 'Board game enthusiast'],
    linkedin_url: 'https://linkedin.com/in/aggie-patterson-00004',
  },
  {
    id: 'contact-018',
    name: 'Agnes Chen',
    email: 'agnes.chen@techcorp.com',
    last_meeting: '2024-11-05',
    buyer_persona: 'Finance/Operations Executive',
    company: 'TechCorp',
    job_title: 'Controller',
    location: 'San Jose, California, United States',
    activity_summary: 'Last spoke with them on November 5, 2024 about financial reporting automation and enterprise resource planning.',
    personal_markers: ['Badminton enthusiast - plays in league', 'Recently bought a vacation home in Lake Tahoe', 'Learning Mandarin with app'],
    linkedin_url: 'https://linkedin.com/in/agnes-chen-00005',
  },
];
