import { Contact } from '@/components/ContactsPage';

export const contactsData: Contact[] = [
  {
    id: 'contact-001',
    name: '/vilanova/',
    email: 'mike.vilanova@equinox.com',
    last_meeting: '2024-11-24',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Equinox',
    personal_markers: ['Huge NY Giants fan', 'Just got back from Miami trip', 'Mentioned wanting to learn golf'],
    linkedin_url: 'https://linkedin.com/in/mike-vilanova-12345',
  },
  {
    id: 'contact-002',
    name: 'Aasiyah Abdulsalam',
    email: 'aasiyah@therenatural.com',
    last_meeting: '2024-11-07',
    buyer_persona: 'Technical Implementation Lead',
    company: 'The Natural',
    personal_markers: ['Basketball enthusiast - supports Warriors', 'Recently promoted to senior engineer role', 'Has a passion for outdoor hiking'],
    linkedin_url: 'https://linkedin.com/in/aasiyah-abdulsalam-98765',
  },
  {
    id: 'contact-003',
    name: 'Abate, Jessica',
    email: 'jabate@sac.shiseido.com',
    last_meeting: '2024-09-11',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Shiseido',
    personal_markers: ['Avid reader - loves mystery novels', 'Just celebrated 15 years at Shiseido', 'Mentioned upcoming wedding in Japan'],
    linkedin_url: 'https://linkedin.com/in/jessica-abate-54321',
  },
  {
    id: 'contact-004',
    name: 'Abbas Ajmeri',
    email: 'abbas@medicaleshop.com',
    last_meeting: '2024-10-06',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'Medical eShop',
    personal_markers: ['Soccer fan - supports Manchester United', 'Recently became a father', 'Learning to cook Middle Eastern cuisine'],
    linkedin_url: 'https://linkedin.com/in/abbas-ajmeri-76543',
  },
  {
    id: 'contact-005',
    name: 'Abby Armijo',
    email: 'aarmijo@adcopros.com',
    last_meeting: '2024-09-19',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'ADCO Pros',
    personal_markers: ['Tennis player - plays weekly matches', 'Recently launched podcast about startups', 'Dog lover - has two golden retrievers'],
    linkedin_url: 'https://linkedin.com/in/abby-armijo-11111',
  },
  {
    id: 'contact-006',
    name: 'Abby Burke',
    email: 'abby.burke@underdogteam.com',
    last_meeting: '2024-12-02',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Underdog',
    personal_markers: ['Boston Red Sox fan since childhood', 'Took a sabbatical last year to travel', 'Recently completed MBA in Finance'],
    linkedin_url: 'https://linkedin.com/in/abby-burke-22222',
  },
  {
    id: 'contact-007',
    name: 'Abigail Miller',
    email: 'abigail@myfirmtech.com',
    last_meeting: '2024-11-14',
    buyer_persona: 'Technical Implementation Lead',
    company: 'MyFirm Tech',
    personal_markers: ['Indie video game enthusiast', 'Recently moved to Seattle from Austin', 'Volunteers with local tech mentorship program'],
    linkedin_url: 'https://linkedin.com/in/abigail-miller-33333',
  },
  {
    id: 'contact-008',
    name: 'Adam DYER',
    email: 'adam.dyer@loreal.com',
    last_meeting: '2024-12-12',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'L\'Oreal',
    personal_markers: ['Rugby fan - watches international matches', 'Fluent in 3 languages', 'Recently completed marathon in Paris'],
    linkedin_url: 'https://linkedin.com/in/adam-dyer-44444',
  },
  {
    id: 'contact-009',
    name: 'Ádám Nagyházy-Horváth',
    email: 'nagyhazy-horvath@biotia.io',
    last_meeting: '2024-10-06',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'Biotia',
    personal_markers: ['Handball player - coaches local youth team', 'Recently visited family in Budapest', 'Passionate about biotech education'],
    linkedin_url: 'https://linkedin.com/in/adam-nagyhazy-horvath-55555',
  },
  {
    id: 'contact-010',
    name: 'Adan from Studio 31',
    email: 'hello@studio31.io',
    last_meeting: '2024-11-12',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Studio 31',
    personal_markers: ['Photography hobbyist - does weekend shoots', 'Just bought a house in Portland', 'Collecting vinyl records'],
    linkedin_url: 'https://linkedin.com/in/adan-studio31-66666',
  },
  {
    id: 'contact-011',
    name: 'Adria Aparisi',
    email: 'adria.aparisi@isdin.com',
    last_meeting: '2024-12-18',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'ISDIN',
    personal_markers: ['Barcelona football fan since childhood', 'Just launched a wellness blog', 'Rock climbing enthusiast'],
    linkedin_url: 'https://linkedin.com/in/adria-aparisi-77777',
  },
  {
    id: 'contact-012',
    name: 'Adrian Schmidt',
    email: 'adrian@techventure.com',
    last_meeting: '2024-09-30',
    buyer_persona: 'Technical Implementation Lead',
    company: 'TechVenture',
    personal_markers: ['Cycling enthusiast - commutes by bike', 'Recently became a German citizen', 'Homebrewing beer as a hobby'],
    linkedin_url: 'https://linkedin.com/in/adrian-schmidt-88888',
  },
  {
    id: 'contact-013',
    name: 'Adriana Gomez',
    email: 'adriana.gomez@innovations.com',
    last_meeting: '2024-11-20',
    buyer_persona: 'Finance/Operations Executive',
    company: 'Innovations Inc',
    personal_markers: ['Salsa dancer - competes at local level', 'Recently promoted to CFO', 'Mentors young women in finance'],
    linkedin_url: 'https://linkedin.com/in/adriana-gomez-99999',
  },
  {
    id: 'contact-014',
    name: 'Aeron Mills',
    email: 'aeron@marketingplus.com',
    last_meeting: '2024-10-15',
    buyer_persona: 'Technical Founder/Decision Maker',
    company: 'Marketing Plus',
    personal_markers: ['Avid skier - goes to Colorado every winter', 'Fascinated by Japanese culture', 'Recently adopted a rescue dog'],
    linkedin_url: 'https://linkedin.com/in/aeron-mills-00001',
  },
  {
    id: 'contact-015',
    name: 'Agatha Ford',
    email: 'agatha.ford@enterprise.com',
    last_meeting: '2024-12-08',
    buyer_persona: 'Operations/Implementation Manager',
    company: 'Enterprise Corp',
    personal_markers: ['Marathon runner - completed Boston Marathon', 'Plant parent - has a whole greenhouse', 'Gardening Instagram influencer'],
    linkedin_url: 'https://linkedin.com/in/agatha-ford-00002',
  },
  {
    id: 'contact-016',
    name: 'Agatha Williams',
    email: 'agatha.williams@solutions.io',
    last_meeting: '2024-11-01',
    buyer_persona: 'Marketing/Growth Leader',
    company: 'Solutions.io',
    personal_markers: ['Jazz music lover - plays saxophone', 'Recently traveled to Morocco', 'Vegan chef enthusiast'],
    linkedin_url: 'https://linkedin.com/in/agatha-williams-00003',
  },
  {
    id: 'contact-017',
    name: 'Aggie Patterson',
    email: 'aggie.p@growthco.com',
    last_meeting: '2024-10-28',
    buyer_persona: 'Technical Implementation Lead',
    company: 'GrowthCo',
    personal_markers: ['Triathlon competitor - qualifying for nationals', 'Recently moved to San Francisco', 'Board game enthusiast'],
    linkedin_url: 'https://linkedin.com/in/aggie-patterson-00004',
  },
  {
    id: 'contact-018',
    name: 'Agnes Chen',
    email: 'agnes.chen@techcorp.com',
    last_meeting: '2024-11-05',
    buyer_persona: 'Finance/Operations Executive',
    company: 'TechCorp',
    personal_markers: ['Badminton enthusiast - plays in league', 'Recently bought a vacation home in Lake Tahoe', 'Learning Mandarin with app'],
    linkedin_url: 'https://linkedin.com/in/agnes-chen-00005',
  },
];
