import { Deal } from '@/types';

export const dealsData: Deal[] = [
  {
    id: 'deal-001',
    stage_name: 'First meeting scheduled',
    name: 'Deal with ggfitness.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-06',
    next_meeting: '2026-01-15',
    owner_name: 'Sarah Chen',
    company_name: 'GG Fitness',
    company_icon_color: 'bg-amber-200',
    company_logo_url: 'https://logo.clearbit.com/ggfitness.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process', 'Paper Process'],
    },
  },
  {
    id: 'deal-002',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with tricoci.com',
    icon_color: 'bg-gray-300',
    momentum: 'Stalled',
    last_meeting: '2026-01-06',
    next_meeting: '2026-01-15',
    owner_name: 'James Miller',
    company_name: 'Tricoci',
    company_icon_color: 'bg-pink-200',
    company_logo_url: 'https://logo.clearbit.com/tricoci.com',
    status: 'in_progress',
  },
  {
    id: 'deal-003',
    stage_name: 'Demo',
    name: 'Deal with fit52.com',
    icon_color: 'bg-gray-300',
    momentum: 'At risk',
    last_meeting: '2026-01-06',
    next_meeting: null,
    owner_name: 'Emily Davis',
    company_name: 'Fit52',
    company_icon_color: 'bg-sky-200',
    company_logo_url: 'https://logo.clearbit.com/fit52.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 1,
      partial: 4,
      missing: 2,
      gaps: ['Metrics', 'Decision Maker'],
    },
  },
  {
    id: 'deal-004',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with cryomedics.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-06',
    next_meeting: '2026-01-15',
    owner_name: 'Alex Johnson',
    company_name: 'Cryomedics',
    company_icon_color: 'bg-teal-200',
    company_logo_url: 'https://logo.clearbit.com/cryomedics.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 2,
      missing: 2,
      gaps: [],
    },
  },
  {
    id: 'deal-005',
    stage_name: 'Demo',
    name: 'Deal with proven.com',
    icon_color: 'bg-blue-200',
    momentum: 'Active',
    last_meeting: '2026-01-06',
    next_meeting: null,
    owner_name: 'Maria Lopez',
    company_name: 'PROVEN Skincare',
    company_icon_color: 'bg-violet-200',
    company_logo_url: 'https://logo.clearbit.com/provenskincare.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 4,
      partial: 1,
      missing: 2,
      gaps: ['Economic Buyer'],
    },
  },
  {
    id: 'deal-006',
    stage_name: 'Closed Lost',
    name: 'Deal with flexhq.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2026-01-06',
    next_meeting: null,
    owner_name: 'David Park',
    company_name: 'Flex',
    company_icon_color: 'bg-emerald-200',
    company_logo_url: 'https://logo.clearbit.com/withflex.com',
    status: 'lost',
    meddic_completion: {
      complete: 2,
      partial: 2,
      missing: 3,
      gaps: ['Decision Maker', 'Economic Buyer', 'Buying Process'],
    },
  },
  {
    id: 'deal-007',
    stage_name: 'First meeting scheduled',
    name: 'Deal with allbirds.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-03',
    next_meeting: '2026-01-12',
    owner_name: 'Sarah Chen',
    company_name: 'Allbirds',
    company_icon_color: 'bg-lime-200',
    company_logo_url: 'https://logo.clearbit.com/allbirds.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 2,
      missing: 5,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-008',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with glossier.com',
    icon_color: 'bg-gray-300',
    momentum: 'At risk',
    last_meeting: '2026-01-04',
    next_meeting: null,
    owner_name: 'James Miller',
    company_name: 'Glossier',
    company_icon_color: 'bg-pink-300',
    company_logo_url: 'https://logo.clearbit.com/glossier.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 3,
      missing: 1,
      gaps: ['Buying Process'],
    },
  },
  {
    id: 'deal-009',
    stage_name: 'First meeting scheduled',
    name: 'Deal with warbyparker.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: null,
    next_meeting: '2026-01-20',
    owner_name: 'Emily Davis',
    company_name: 'Warby Parker',
    company_icon_color: 'bg-blue-200',
    company_logo_url: 'https://logo.clearbit.com/warbyparker.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-010',
    stage_name: 'Demo',
    name: 'Deal with bombas.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-05',
    next_meeting: '2026-01-16',
    owner_name: 'Alex Johnson',
    company_name: 'Bombas',
    company_icon_color: 'bg-orange-200',
    company_logo_url: 'https://logo.clearbit.com/bombas.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 2,
      partial: 2,
      missing: 3,
      gaps: ['Economic Buyer', 'Buying Process'],
    },
  },
  {
    id: 'deal-011',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with casper.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: '2026-01-07',
    next_meeting: '2026-01-22',
    owner_name: 'Sarah Chen',
    company_name: 'Casper',
    company_icon_color: 'bg-indigo-200',
    company_logo_url: 'https://logo.clearbit.com/casper.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 4,
      partial: 2,
      missing: 1,
      gaps: [],
    },
  },
  {
    id: 'deal-012',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with away.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-08',
    next_meeting: null,
    owner_name: 'Maria Lopez',
    company_name: 'Away',
    company_icon_color: 'bg-cyan-200',
    company_logo_url: 'https://logo.clearbit.com/awaytravel.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 3,
      missing: 1,
      gaps: ['Economic Buyer'],
    },
  },
  {
    id: 'deal-013',
    stage_name: 'Demo',
    name: 'Deal with brooklinen.com',
    icon_color: 'bg-gray-300',
    momentum: 'Stalled',
    last_meeting: '2026-01-02',
    next_meeting: null,
    owner_name: 'David Park',
    company_name: 'Brooklinen',
    company_icon_color: 'bg-slate-200',
    company_logo_url: 'https://logo.clearbit.com/brooklinen.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 4,
      partial: 2,
      missing: 1,
      gaps: ['Decision Maker'],
    },
  },
  {
    id: 'deal-014',
    stage_name: 'First meeting scheduled',
    name: 'Deal with hims.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: null,
    next_meeting: '2026-01-25',
    owner_name: 'Alex Johnson',
    company_name: 'Hims & Hers',
    company_icon_color: 'bg-rose-200',
    company_logo_url: 'https://logo.clearbit.com/forhims.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 0,
      missing: 7,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-015',
    stage_name: 'Closed Won',
    name: 'Deal with rothy.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-20',
    next_meeting: null,
    owner_name: 'Emily Davis',
    company_name: "Rothy's",
    company_icon_color: 'bg-teal-200',
    company_logo_url: 'https://logo.clearbit.com/rothys.com',
    status: 'won',
    meddic_completion: {
      complete: 1,
      partial: 4,
      missing: 2,
      gaps: ['Metrics', 'Decision Maker'],
    },
  },
  {
    id: 'deal-016',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with olipop.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-09',
    next_meeting: '2026-01-23',
    owner_name: 'James Miller',
    company_name: 'Olipop',
    company_icon_color: 'bg-yellow-200',
    company_logo_url: 'https://logo.clearbit.com/drinkolipop.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 5,
      partial: 2,
      missing: 0,
      gaps: [],
    },
  },
  {
    id: 'deal-017',
    stage_name: 'Demo',
    name: 'Deal with mejuri.com',
    icon_color: 'bg-gray-300',
    momentum: 'At risk',
    last_meeting: '2026-01-03',
    next_meeting: '2026-01-17',
    owner_name: 'Sarah Chen',
    company_name: 'Mejuri',
    company_icon_color: 'bg-amber-200',
    company_logo_url: 'https://logo.clearbit.com/mejuri.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 2,
      missing: 2,
      gaps: ['Buying Process'],
    },
  },
  {
    id: 'deal-018',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with figs.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: '2026-01-10',
    next_meeting: null,
    owner_name: 'Maria Lopez',
    company_name: 'FIGS',
    company_icon_color: 'bg-violet-200',
    company_logo_url: 'https://logo.clearbit.com/wearfigs.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 2,
      partial: 4,
      missing: 1,
      gaps: [],
    },
  },
  {
    id: 'deal-019',
    stage_name: 'Closed Lost',
    name: 'Deal with quip.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-18',
    next_meeting: null,
    owner_name: 'David Park',
    company_name: 'Quip',
    company_icon_color: 'bg-sky-200',
    company_logo_url: 'https://logo.clearbit.com/getquip.com',
    status: 'lost',
    meddic_completion: {
      complete: 4,
      partial: 1,
      missing: 2,
      gaps: ['Economic Buyer', 'Decision Maker'],
    },
  },
  {
    id: 'deal-020',
    stage_name: 'First meeting scheduled',
    name: 'Deal with ritual.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: null,
    next_meeting: '2026-01-28',
    owner_name: 'Alex Johnson',
    company_name: 'Ritual',
    company_icon_color: 'bg-yellow-200',
    company_logo_url: 'https://logo.clearbit.com/ritual.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-021',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with nativecos.com',
    icon_color: 'bg-gray-300',
    momentum: 'Stalled',
    last_meeting: '2026-01-01',
    next_meeting: null,
    owner_name: 'Emily Davis',
    company_name: 'Native',
    company_icon_color: 'bg-emerald-200',
    company_logo_url: 'https://logo.clearbit.com/nativecos.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 2,
      missing: 2,
      gaps: ['Metrics', 'Buying Process'],
    },
  },
  {
    id: 'deal-022',
    stage_name: 'Demo',
    name: 'Deal with untuckit.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: '2026-01-11',
    next_meeting: '2026-01-26',
    owner_name: 'James Miller',
    company_name: 'UNTUCKit',
    company_icon_color: 'bg-blue-200',
    company_logo_url: 'https://logo.clearbit.com/untuckit.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 1,
      partial: 3,
      missing: 3,
      gaps: ['Economic Buyer', 'Buying Process'],
    },
  },
  {
    id: 'deal-023',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with peloton.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-10',
    next_meeting: '2026-01-21',
    owner_name: 'Sarah Chen',
    company_name: 'Peloton',
    company_icon_color: 'bg-red-200',
    company_logo_url: 'https://logo.clearbit.com/onepeloton.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 4,
      partial: 3,
      missing: 0,
      gaps: [],
    },
  },
  {
    id: 'deal-024',
    stage_name: 'Closed Won',
    name: 'Deal with drizly.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-15',
    next_meeting: null,
    owner_name: 'Maria Lopez',
    company_name: 'Drizly',
    company_icon_color: 'bg-orange-200',
    company_logo_url: 'https://logo.clearbit.com/drizly.com',
    status: 'won',
    meddic_completion: {
      complete: 4,
      partial: 1,
      missing: 2,
      gaps: ['Decision Maker'],
    },
  },
  {
    id: 'deal-025',
    stage_name: 'First meeting scheduled',
    name: 'Deal with thirdlove.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: null,
    next_meeting: '2026-01-30',
    owner_name: 'David Park',
    company_name: 'ThirdLove',
    company_icon_color: 'bg-pink-200',
    company_logo_url: 'https://logo.clearbit.com/thirdlove.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-026',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with lulus.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-12',
    next_meeting: '2026-01-27',
    owner_name: 'Alex Johnson',
    company_name: "Lulu's",
    company_icon_color: 'bg-fuchsia-200',
    company_logo_url: 'https://logo.clearbit.com/lulus.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 2,
      partial: 4,
      missing: 1,
      gaps: ['Buying Process'],
    },
  },
  {
    id: 'deal-027',
    stage_name: 'Demo',
    name: 'Deal with agorabrandsgroup.com',
    icon_color: 'bg-gray-300',
    momentum: 'At risk',
    last_meeting: '2026-01-05',
    next_meeting: '2026-01-19',
    owner_name: 'Emily Davis',
    company_name: 'Agora Brands',
    company_icon_color: 'bg-lime-200',
    company_logo_url: 'https://logo.clearbit.com/agorabrandsgroup.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 3,
      missing: 1,
      gaps: ['Metrics'],
    },
  },
  {
    id: 'deal-028',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with oura.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: '2026-01-13',
    next_meeting: '2026-01-29',
    owner_name: 'James Miller',
    company_name: 'Oura',
    company_icon_color: 'bg-zinc-200',
    company_logo_url: 'https://logo.clearbit.com/ouraring.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 2,
      partial: 2,
      missing: 3,
      gaps: ['Economic Buyer', 'Decision Maker'],
    },
  },
  {
    id: 'deal-029',
    stage_name: 'First meeting scheduled',
    name: 'Deal with cotopaxi.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: null,
    next_meeting: '2026-02-01',
    owner_name: 'Sarah Chen',
    company_name: 'Cotopaxi',
    company_icon_color: 'bg-orange-200',
    company_logo_url: 'https://logo.clearbit.com/cotopaxi.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-030',
    stage_name: 'Closed Lost',
    name: 'Deal with brandless.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-10',
    next_meeting: null,
    owner_name: 'Maria Lopez',
    company_name: 'Brandless',
    company_icon_color: 'bg-gray-200',
    company_logo_url: 'https://logo.clearbit.com/brandless.com',
    status: 'lost',
    meddic_completion: {
      complete: 3,
      partial: 3,
      missing: 1,
      gaps: ['Decision Maker'],
    },
  },
  {
    id: 'deal-031',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with barkbox.com',
    icon_color: 'bg-gray-300',
    momentum: 'Stalled',
    last_meeting: '2026-01-02',
    next_meeting: null,
    owner_name: 'David Park',
    company_name: 'BarkBox',
    company_icon_color: 'bg-amber-200',
    company_logo_url: 'https://logo.clearbit.com/barkbox.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 5,
      partial: 2,
      missing: 0,
      gaps: [],
    },
  },
  {
    id: 'deal-032',
    stage_name: 'Demo',
    name: 'Deal with vuoriclothing.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-14',
    next_meeting: '2026-01-28',
    owner_name: 'Alex Johnson',
    company_name: 'Vuori',
    company_icon_color: 'bg-teal-200',
    company_logo_url: 'https://logo.clearbit.com/vuoriclothing.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 1,
      partial: 4,
      missing: 2,
      gaps: ['Economic Buyer', 'Buying Process'],
    },
  },
  {
    id: 'deal-033',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with koio.co',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: '2026-01-11',
    next_meeting: '2026-01-25',
    owner_name: 'Emily Davis',
    company_name: 'Koio',
    company_icon_color: 'bg-stone-200',
    company_logo_url: 'https://logo.clearbit.com/koio.co',
    status: 'in_progress',
    meddic_completion: {
      complete: 4,
      partial: 2,
      missing: 1,
      gaps: [],
    },
  },
  {
    id: 'deal-034',
    stage_name: 'First meeting scheduled',
    name: 'Deal with hydroflask.com',
    icon_color: 'bg-gray-300',
    momentum: 'Active',
    last_meeting: null,
    next_meeting: '2026-02-03',
    owner_name: 'James Miller',
    company_name: 'Hydro Flask',
    company_icon_color: 'bg-cyan-200',
    company_logo_url: 'https://logo.clearbit.com/hydroflask.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-035',
    stage_name: 'Closed Won',
    name: 'Deal with everlane.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-22',
    next_meeting: null,
    owner_name: 'Sarah Chen',
    company_name: 'Everlane',
    company_icon_color: 'bg-neutral-200',
    company_logo_url: 'https://logo.clearbit.com/everlane.com',
    status: 'won',
    meddic_completion: {
      complete: 2,
      partial: 3,
      missing: 2,
      gaps: ['Decision Maker'],
    },
  },
  {
    id: 'deal-036',
    stage_name: 'Discovery & Qualification',
    name: 'Deal with parachutehome.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: '2026-01-09',
    next_meeting: '2026-01-23',
    owner_name: 'Maria Lopez',
    company_name: 'Parachute',
    company_icon_color: 'bg-sky-200',
    company_logo_url: 'https://logo.clearbit.com/parachutehome.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 5,
      partial: 2,
      missing: 0,
      gaps: [],
    },
  },
  {
    id: 'deal-037',
    stage_name: 'Demo',
    name: 'Deal with outdoor-voices.com',
    icon_color: 'bg-gray-300',
    momentum: 'At risk',
    last_meeting: '2026-01-04',
    next_meeting: '2026-01-18',
    owner_name: 'David Park',
    company_name: 'Outdoor Voices',
    company_icon_color: 'bg-lime-200',
    company_logo_url: 'https://logo.clearbit.com/outdoorvoices.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 3,
      partial: 3,
      missing: 1,
      gaps: ['Buying Process'],
    },
  },
  {
    id: 'deal-038',
    stage_name: 'Proposal / Negotiation',
    name: 'Deal with framebridge.com',
    icon_color: 'bg-gray-300',
    momentum: 'Stalled',
    last_meeting: '2026-01-06',
    next_meeting: null,
    owner_name: 'Alex Johnson',
    company_name: 'Framebridge',
    company_icon_color: 'bg-amber-200',
    company_logo_url: 'https://logo.clearbit.com/framebridge.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 2,
      partial: 4,
      missing: 1,
      gaps: ['Economic Buyer'],
    },
  },
  {
    id: 'deal-039',
    stage_name: 'First meeting scheduled',
    name: 'Deal with alo.com',
    icon_color: 'bg-gray-300',
    momentum: 'Strong',
    last_meeting: null,
    next_meeting: '2026-02-05',
    owner_name: 'Emily Davis',
    company_name: 'Alo Yoga',
    company_icon_color: 'bg-violet-200',
    company_logo_url: 'https://logo.clearbit.com/aloyoga.com',
    status: 'in_progress',
    meddic_completion: {
      complete: 0,
      partial: 1,
      missing: 6,
      gaps: ['Metrics', 'Economic Buyer', 'Decision Maker', 'Buying Process'],
    },
  },
  {
    id: 'deal-040',
    stage_name: 'Closed Lost',
    name: 'Deal with winc.com',
    icon_color: 'bg-gray-300',
    momentum: 'Closed',
    last_meeting: '2025-12-08',
    next_meeting: null,
    owner_name: 'James Miller',
    company_name: 'Winc',
    company_icon_color: 'bg-red-200',
    company_logo_url: 'https://logo.clearbit.com/winc.com',
    status: 'lost',
    meddic_completion: {
      complete: 3,
      partial: 2,
      missing: 2,
      gaps: ['Buying Process'],
    },
  },
];
