import { PastMeeting } from '@/types';

export const pastMeetingsData: PastMeeting[] = [
  // Fri 6 Feb
  {
    id: 'pm-001',
    deal_name: 'Cal AI',
    momentum: 'Strong',
    name: 'Eugene Kim and Benny Cole',
    start_time: '2026-02-06T09:00:00',
    duration: '30m',
    company_name: 'Cal AI',
    company_icon_color: 'bg-blue-200',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales' },
      { name: 'Eugene Kim', email: 'eugene@calai.io', role: 'Co-founder' },
    ],
  },
  {
    id: 'pm-002',
    deal_name: 'Cal AI HSA/FSA',
    momentum: 'Strong',
    name: 'Cal AI x Flex HSA/FSA',
    status: 'Processing',
    start_time: '2026-02-06T09:00:00',
    duration: '30m',
    company_name: 'Cal AI',
    company_icon_color: 'bg-blue-200',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager' },
      { name: 'Benny Cole', email: 'benny@calai.io', role: 'Head of Operations' },
    ],
  },
  {
    id: 'pm-003',
    deal_name: 'WW Partnership',
    momentum: 'Active',
    name: 'WW <> Flex',
    start_time: '2026-02-06T10:00:00',
    duration: '30m',
    company_name: 'WW',
    company_icon_color: 'bg-indigo-200',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development' },
      { name: 'Rachel Simmons', email: 'r.simmons@ww.com', role: 'Partnership Manager' },
    ],
  },
  {
    id: 'pm-004',
    deal_name: 'Glossier',
    momentum: 'At risk',
    name: 'Glossier <> Flex',
    start_time: '2026-02-06T10:30:00',
    duration: '30m',
    company_name: 'Glossier',
    company_icon_color: 'bg-pink-300',
    company_logo_url: 'https://logo.clearbit.com/glossier.com',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager' },
      { name: 'Diana Voss', email: 'diana.voss@glossier.com', role: 'Operations Lead' },
    ],
  },
  // Thu 5 Feb
  {
    id: 'pm-005',
    deal_name: 'Nourish',
    momentum: 'Stalled',
    name: 'Nourish x Flex Partnership',
    status: 'Error',
    start_time: '2026-02-05T10:30:00',
    duration: '30m',
    company_name: 'Nourish',
    company_icon_color: 'bg-lime-200',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales' },
      { name: 'Amir Patel', email: 'apatel@nourish.com', role: 'Chief Product Officer' },
    ],
  },
  {
    id: 'pm-006',
    deal_name: 'Hims & Hers',
    momentum: 'Active',
    name: 'Hims & Hers <> Flex',
    start_time: '2026-02-05T11:00:00',
    duration: '45m',
    company_name: 'Hims & Hers',
    company_icon_color: 'bg-rose-200',
    company_logo_url: 'https://logo.clearbit.com/forhims.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development' },
      { name: 'Priya Mehta', email: 'p.mehta@forhims.com', role: 'Sr. Product Manager' },
    ],
  },
  {
    id: 'pm-007',
    deal_name: 'Ro Health',
    momentum: 'Strong',
    name: 'Ro Health Benefits Review',
    start_time: '2026-02-05T14:00:00',
    duration: '30m',
    company_name: 'Ro',
    company_icon_color: 'bg-sky-200',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager' },
      { name: 'David Kwon', email: 'd.kwon@ro.com', role: 'Director of Benefits' },
    ],
  },
  // Wed 4 Feb
  {
    id: 'pm-008',
    deal_name: 'Allbirds',
    momentum: 'Strong',
    name: 'Allbirds Intro Call',
    start_time: '2026-02-04T09:30:00',
    duration: '30m',
    company_name: 'Allbirds',
    company_icon_color: 'bg-lime-200',
    company_logo_url: 'https://logo.clearbit.com/allbirds.com',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales' },
      { name: 'Liam Okafor', email: 'l.okafor@allbirds.com', role: 'Director of Procurement' },
    ],
  },
  {
    id: 'pm-009',
    deal_name: 'Bombas',
    momentum: 'Strong',
    name: 'Bombas <> Flex Demo',
    start_time: '2026-02-04T11:00:00',
    duration: '45m',
    company_name: 'Bombas',
    company_icon_color: 'bg-orange-200',
    company_logo_url: 'https://logo.clearbit.com/bombas.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development' },
      { name: 'Sophie Grant', email: 's.grant@bombas.com', role: 'Contract Manager' },
    ],
  },
  // Tue 3 Feb
  {
    id: 'pm-010',
    deal_name: 'Peloton',
    momentum: 'Strong',
    name: 'Peloton Partnership Sync',
    start_time: '2026-02-03T10:00:00',
    duration: '30m',
    company_name: 'Peloton',
    company_icon_color: 'bg-red-200',
    company_logo_url: 'https://logo.clearbit.com/onepeloton.com',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales' },
      { name: 'Carlos Reyes', email: 'c.reyes@peloton.com', role: 'Engineering Manager' },
    ],
  },
  {
    id: 'pm-011',
    deal_name: 'Alma Wellness',
    momentum: 'Active',
    name: 'Alma x Flex Wellness',
    status: 'Processing',
    start_time: '2026-02-03T13:00:00',
    duration: '30m',
    company_name: 'Alma',
    company_icon_color: 'bg-pink-200',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager' },
      { name: 'Hannah Torres', email: 'h.torres@alma.com', role: 'Partnerships Lead' },
    ],
  },
  {
    id: 'pm-012',
    deal_name: 'Warby Parker',
    momentum: 'Active',
    name: 'Warby Parker Follow-up',
    start_time: '2026-02-03T15:30:00',
    duration: '30m',
    company_name: 'Warby Parker',
    company_icon_color: 'bg-blue-200',
    company_logo_url: 'https://logo.clearbit.com/warbyparker.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development' },
      { name: 'Andrea Chen', email: 'a.chen@warbyparker.com', role: 'Finance Manager' },
    ],
  },
  // Mon 2 Feb
  {
    id: 'pm-013',
    deal_name: 'Oura',
    momentum: 'Active',
    name: 'Oura Health Check-in',
    start_time: '2026-02-02T09:00:00',
    duration: '30m',
    company_name: 'Oura',
    company_icon_color: 'bg-zinc-200',
    company_logo_url: 'https://logo.clearbit.com/ouraring.com',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager' },
      { name: 'Tomoko Sato', email: 't.sato@ouraring.com', role: 'Solutions Architect' },
    ],
  },
  {
    id: 'pm-014',
    deal_name: 'Truepill',
    momentum: 'Stalled',
    name: 'Truepill <> Flex Integration',
    start_time: '2026-02-02T14:00:00',
    duration: '45m',
    company_name: 'Truepill',
    company_icon_color: 'bg-purple-200',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales' },
      { name: 'Marcus Webb', email: 'm.webb@truepill.com', role: 'VP Engineering' },
    ],
  },
];
