import { PastMeeting } from '@/types';

// Reusing PastMeeting type since the structure is the same
export const upcomingMeetingsData: PastMeeting[] = [
  // Mon 16 Feb
  {
    id: 'um-001',
    deal_name: 'PROVEN Skincare',
    momentum: 'Strong',
    name: 'PROVEN <> Flex',
    status: 'Recording',
    start_time: '2026-02-16T17:00:00',
    duration: '60m',
    company_name: 'PROVEN Skincare',
    company_icon_color: 'bg-green-200',
    attendees: [
      { name: 'Jacob Francis', email: 'jacob@flex.com', role: 'VP Sales', contact_role: 'seller', linkedin_url: 'https://linkedin.com/in/jacobfrancis' },
      { name: 'Russell Harris', email: 'r.harris@proven.com', role: 'Head of Marketing', contact_role: 'buyer', linkedin_url: 'https://linkedin.com/in/russellharris', persona: 'Technical Founder / Decision Maker', tags: ['Champion', 'Economic Buyer'] },
    ],
  },
  {
    id: 'um-002',
    deal_name: 'Glossier',
    momentum: 'At risk',
    name: 'Glossier <> Flex Follow-up',
    status: 'Now',
    start_time: '2026-02-16T14:00:00',
    duration: '30m',
    company_name: 'Glossier',
    company_icon_color: 'bg-pink-300',
    company_logo_url: 'https://logo.clearbit.com/glossier.com',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager', contact_role: 'seller', linkedin_url: 'https://linkedin.com/in/morganclark' },
      { name: 'Diana Voss', email: 'diana.voss@glossier.com', role: 'Operations Lead', contact_role: 'buyer', linkedin_url: 'https://linkedin.com/in/dianavoss', persona: 'Operations/Implementation Manager', tags: ['Influencer'] },
    ],
  },
  // Tue 17 Feb
  {
    id: 'um-003',
    deal_name: 'Hims & Hers',
    momentum: 'Active',
    name: 'Hims & Hers Quarterly Review',
    start_time: '2026-02-17T10:00:00',
    duration: '45m',
    company_name: 'Hims & Hers',
    company_icon_color: 'bg-rose-200',
    company_logo_url: 'https://logo.clearbit.com/forhims.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development', contact_role: 'seller', linkedin_url: 'https://linkedin.com/in/nickholland' },
      { name: 'Priya Mehta', email: 'p.mehta@forhims.com', role: 'Sr. Product Manager', contact_role: 'buyer', linkedin_url: 'https://linkedin.com/in/priyamehta', persona: 'Marketing/Growth Leader', tags: ['Champion'] },
    ],
  },
  {
    id: 'um-004',
    deal_name: 'Peloton',
    momentum: 'Strong',
    name: 'Peloton Demo Walkthrough',
    start_time: '2026-02-17T13:30:00',
    duration: '30m',
    company_name: 'Peloton',
    company_icon_color: 'bg-red-200',
    company_logo_url: 'https://logo.clearbit.com/onepeloton.com',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales', contact_role: 'seller' },
      { name: 'Carlos Reyes', email: 'c.reyes@peloton.com', role: 'Engineering Manager', contact_role: 'buyer' },
    ],
  },
  // Wed 18 Feb
  {
    id: 'um-005',
    deal_name: 'Oura',
    momentum: 'Active',
    name: 'Oura Integration Planning',
    start_time: '2026-02-18T11:00:00',
    duration: '30m',
    company_name: 'Oura',
    company_icon_color: 'bg-zinc-200',
    company_logo_url: 'https://logo.clearbit.com/ouraring.com',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager', contact_role: 'seller' },
      { name: 'Tomoko Sato', email: 't.sato@ouraring.com', role: 'Solutions Architect', contact_role: 'buyer' },
    ],
  },
  {
    id: 'um-006',
    deal_name: 'Warby Parker',
    momentum: 'Active',
    name: 'Warby Parker Proposal Review',
    start_time: '2026-02-18T15:00:00',
    duration: '45m',
    company_name: 'Warby Parker',
    company_icon_color: 'bg-blue-200',
    company_logo_url: 'https://logo.clearbit.com/warbyparker.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development', contact_role: 'seller' },
      { name: 'Andrea Chen', email: 'a.chen@warbyparker.com', role: 'Finance Manager', contact_role: 'buyer' },
    ],
  },
  // Thu 19 Feb
  {
    id: 'um-007',
    deal_name: 'Allbirds',
    momentum: 'Strong',
    name: 'Allbirds Contract Negotiation',
    start_time: '2026-02-19T09:00:00',
    duration: '30m',
    company_name: 'Allbirds',
    company_icon_color: 'bg-lime-200',
    company_logo_url: 'https://logo.clearbit.com/allbirds.com',
    attendees: [
      { name: 'Jacob Francis', email: 'jfrancis@flex.com', role: 'VP Sales', contact_role: 'seller' },
      { name: 'Liam Okafor', email: 'l.okafor@allbirds.com', role: 'Director of Procurement', contact_role: 'buyer' },
    ],
  },
  {
    id: 'um-008',
    deal_name: 'Cal AI',
    momentum: 'Strong',
    name: 'Cal AI Weekly Sync',
    start_time: '2026-02-19T14:00:00',
    duration: '30m',
    company_name: 'Cal AI',
    company_icon_color: 'bg-blue-200',
    attendees: [
      { name: 'Morgan Clark', email: 'mclark@flex.com', role: 'Product Manager', contact_role: 'seller' },
      { name: 'Eugene Kim', email: 'eugene@calai.io', role: 'Co-founder', contact_role: 'buyer' },
    ],
  },
  // Fri 20 Feb
  {
    id: 'um-009',
    deal_name: 'Bombas',
    momentum: 'Strong',
    name: 'Bombas <> Flex Closing Call',
    start_time: '2026-02-20T10:00:00',
    duration: '30m',
    company_name: 'Bombas',
    company_icon_color: 'bg-orange-200',
    company_logo_url: 'https://logo.clearbit.com/bombas.com',
    attendees: [
      { name: 'Nick Holland', email: 'nholland@flex.com', role: 'Business Development', contact_role: 'seller' },
      { name: 'Sophie Grant', email: 's.grant@bombas.com', role: 'Contract Manager', contact_role: 'buyer' },
    ],
  },
];
